- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Replace case with fromMaybe"
- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use ||"
- ignore:
    name: "Use unless"
- ignore:
    name: "Use const"
- ignore:
    name: "Use record patterns"
