resolver: lts-18.16
packages:
- salsa-party-data
- salsa-party-data-gen
- salsa-party-web-server
- salsa-party-web-server-gen
- salsa-party-web-server-e2e
- salsa-party-web-server-webdriver

# Extra GHC options
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages

extra-deps:
  # TODO use nh2's fixes once they are not broken: https://github.com/Twinside/Juicy.Pixels/pull/215
  # - github: Twinside/Juicy.Pixels
  #   commit: 69e7aef1150f733dfb8b2ce2a008d0160792b752
- github: NorfairKing/ical
  commit: 13b1a3925edf77664324a80f5e62071bea6d0fea
  subdirs:
    - ical
    - ical-gen
- github: NorfairKing/token-limiter-concurrent
  commit: b6829d93a9daf4b9cbe73aae0edeef05597394f2
- github: NorfairKing/looper
  commit: fd36d37becfa04fa4d7e00604e37c61817b6b62b
  subdirs:
    - looper
- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - genvalidity-typed-uuid
    - typed-uuid
- github: NorfairKing/linkcheck
  commit: 90c023208d6f0c49b3057d50b202cfbf92014729
  subdirs:
    - linkcheck
- github: NorfairKing/seocheck
  commit: a6790f7de6ba252bbb4365ab1cc2aaeb0b243ccf
  subdirs:
    - seocheck
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399
- github: NorfairKing/validity
  commit: 657cf4bdc2731387abea6e707b88d381d5218616
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-network-uri
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-network-uri
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: aa42f6951502dba8836d1076c5b6068cdece7b91
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-process
    - sydtest-typed-process
    - sydtest-wai
    - sydtest-webdriver
    - sydtest-webdriver-screenshot
    - sydtest-webdriver-yesod
    - sydtest-yesod
- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0

- github: NorfairKing/autodocodec
  commit: 98135d2b24c4c52f56f53c6650a169aeec61c7f1
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/pretty-relative-time
  commit: a634358ff274380a12360f7814c3aea46ea35b1b


- mime-0.4.0.2@sha256:208947d9d1a19d08850be67ecb28c6e776db697f3bba05bd9d682e51a59f241f,983
- amazonka-1.6.1
- unliftio-core-0.1.2.0@sha256:b0a7652ffce2284a6cebe05c99eb60573a8fb6631163f34b0b30a80b4a78cb23,1081
- webp-0.1.0.1@sha256:f3e9ebf257f898054755747a3987da5bd221e5931e4052c2ac22e3215a4bcb71,2349

system-ghc: true
nix:
  enable: false
with-hpack: hpack
