resolver: lts-16.12
packages:
- salsa-party-web-server
allow-newer: true # Because of token-limiter
extra-deps:
- github: NorfairKing/linkcheck
  commit: 88a325e3a6c8610d1ca380457cd267d87ab2c0ab
  subdirs:
    - linkcheck
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
- yamlparse-applicative-0.1.0.2@sha256:bda91f2818c1b5b124963931cb7f9a4e5758d026c09713e9ae2234534062747d,2133
- github: NorfairKing/yesod-autoreload
  commit: 7135e864c0d4a48efeae473ee2761f5168946e58
- github: NorfairKing/validity
  commit: 549f92de456dd7fbf21b84f2f6fdca9a3c6506d9
  subdirs:
    - genvalidity
    - genvalidity-containers
    - genvalidity-persistent
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - validity
    - validity-containers
    - validity-persistent
    - validity-text
    - validity-time
- github: NorfairKing/safe-coloured-text
  commit: 7f157485e55528648a95edf3508a122b2e55779e
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: 0125c6d6d17d44753c793adc8dcaa4284fef2b7d
  subdirs:
    - sydtest
    - sydtest-discover
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod
- github: NorfairKing/yesod-static-remote
  commit: ed6bf8ef434d49b160429028613a1f6882fccfdf
- token-limiter-0.2.0.3@sha256:7e27a9032e14c3a91f5333f9b87f260a38bcdf6339ef1aa969cdfc49bca75e8b,2321

# https://github.com/commercialhaskell/stackage/blob/766f6f990d85b0b996659a40f54fb73e5545a569/build-constraints.yaml#L1823
- unliftio-core-0.1.2.0
- amazonka-1.6.1
nix:
  shell-file: shell.nix
