# Logo
SalsaPartiesLogo: Salsa Parties Logo

# Home Page
HomeTitle: Salsa Parties Heute
HomeDescription: Wo kann ich tanzen gehen?
HomeSubtitleQuestion: Wo kann ich tanzen gehen?
HomeFormLocation: Mein Standort
HomeFormLocationUnable: Lokalisierung fehlgeschlagen.
HomeFormLocationNotSupported: Geolocation wird von Ihrem Browser nicht unterstützt.
HomeFormLocationInProgress: Lokalisieren…
HomeFormLocationDone: Lokalisiert
HomeFormSearch: Suche
HomeFormHelp: Drücken Sie die Suchtaste, um parties in ihrer Umgebung zu finden.

# Explore
ExploreTitle: Erkunde die Welt des Sozial Dance!
ExploreDescription: Social Dance gibt es auf der ganzen Welt, finde heraus, wohin du gehen kannst!
ExploreButton: Erkunden
ExploreSkylineAlt location@Text: TODO Night-time skyline of #{location}

## Footer
FooterGeocodingAttribution: Geokodierung durch OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap Mitwirkende


# Navbar
NavFind: Party suchen
NavAccount: Konto
NavOrganiser: Veranstalterprofil
NavParties: Meine Partys
NavLanguage: Sprache
NavAdmin: Admin-Panel
NavSignUp: Registrieren
NavLogIn: Anmelden
NavLogOut: Admelden

# Search Results
SearchTitleAroundYourLocationToday: TODO Social dance parties near your location today
SearchTitleAroundYourLocationOnDay day@String: TODO Social dance parties near your location on #{day}
SearchTitleAroundAddressToday address@Text: TODO Social dance parties near #{address} today
SearchTitleAroundAddressOnDay address@Text day@String: TODO Social dance parties near #{address} on #{day}
SearchDescriptionAroundYourLocationToday: TODO A List of social dance parties near your location oday
SearchDescriptionAroundYourLocationOnDay day@String: TODO A List of social dance parties near your location on #{day}
SearchDescriptionAroundAddressToday address@Text: TODO A List of social dance parties near #{address} today
SearchDescriptionAroundAddressOnDay address@Text day@String: TODO A List of social dance parties near #{address} on #{day}
SearchPartiesAroundAddress address@Text: Parties in der Nähe von #{address}
SearchPartiesAroundYourLocation: Parties in deiner Umgebung
SearchNoParties: Es wurden keine Parties gefunden.
SearchPosterAlt title@Text day@String: Poster für #{title} am #{day}.

SearchNavEarlier: Früher
SearchNavLater: Später


# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: ABGESAGT: #{title}
PartyDescription description@Text: TODO #{description}
PartyWithoutDescription: TODO Party without description

PartyAddress address@Text: Addresse: #{address}
PartyOrganiser name@Text: Veranstalter: #{name}
PartyPrice price@Text: Preis: #{price}
PartyHomepage: Webseite
PartyDownloadCalendarEvent: Kalendar-Event herunterladen
PartyAddToGoogleCalendar: Zu Google Kalender hinzufügen

ExternalEventCaution: Event via Websuche gefunden. Behandeln Sie diese Informationen mit Vorsicht. 

# Organiser Page
OrganiserTitle name@Text: TODO Organiser profile: #{name}
OrganiserDescription name@Text: TODO The organiser profile of #{name}, and a list of their upcoming social dance parties
OrganiserName name@Text: Veranstalter: #{name}
OrganiserUpcomingParties: Bevorstehende Parties
OrganiserNoUpcomingParties: Keine bevorstehenden Parties

# Poster
PosterAltFull title@Text day@String organiser@Text: TODO Poster for #{title} on #{day} by #{organiser}.

# Registration
RegistrationTitle: TODO Salsa Parties Today: Registration
RegistrationDescription: TODO Register an account at Salsa Parties Today
RegistrationEmailAddressLabel: TODO Email Address
RegistrationPassphraseLabel: TODO Passphrase
RegistrationConfirmPassphraseLabel: TODO Confirm Passphrase
RegistrationSignUpButton: TODO Sign up
RegistrationLogInButton: TODO Log in
RegistrationErrorAccountAlreadyExists: TODO An account with this username already exists.

# Login
LoginTitle: TODO Salsa Parties Today: Login
LoginDescription: TODO Log into your account at Salsa Parties Today
LoginEmailAddressLabel: TODO Email Address
LoginPassphraseLabel: TODO Passphrase
LoginLogInButton: TODO Log in
LoginSignUpButton: TODO Sign up

# Verification Email
VerificationEmailSubject: TODO Salsa Party Today Email Verification
VerificationEmailTitle: TODO Salsa Party Today Registration
VerificationEmailTextCTA: TODO Please verify your email address by following this link:
VerificationEmailHtmlCTA: TODO Please verify your email address by clicking the link below.
VerificationEmailButton: TODO Verify Email
VerificationEmailInvitation: TODO We hope to see you soon.
VerificationEmailExplanation: TODO You got this email because you tried to register at Salsa Parties Today

VerificationEmailFailure: TODO Failed to send verification email.
VerificationErrorAlreadyVerified: TODO This account is already verified.

# Account Page
AccountOverviewTitle: TODO Account
AccountEmailAddress emailAddress@Text: TODO Email Address: #{emailAddress}
AccountVerificationTitle: TODO Account Verification
AccountVerificationWarning: TODO Your account is not verified yet. You will not be able to submit parties.
AccountVerificationCheckEmail: TODO Please check your email inbox for a verification email.
AccountVerificationCheckEmailDisclaimer: TODO If your verification email has not arrived yet, please make sure to check your spam folder. We do our best to prevent emails from ending up in spam but fail sometimes. If you still do not find a verification email, please contact the site administrators.
AccountVerificationResendButton: TODO Resend Verification Email
AccountDangerZoneTitle: TODO Danger Zone
AccountDeleteButton: TODO Delete Account
AccountDeleteWarning: TODO Are you sure you want to delete your account? This cannot be undone.

# Organiser Profile
OrganiserProfileTitle: TODO Organiser Profile
OrganiserDisplayNameLabel: TODO Display Name
OrganiserSubmitButton: TODO Submit
OrganiserViewPublicProfileButton: TODO View Public Profile

# Your parties
YourPartiesTitle: TODO Your parties
YourPartiesSubmitButton: TODO Submit party
YourPartiesNoParties: TODO You have not submitted any parties yet.
YourPartiesEditPartyButton: TODO Edit
YourPartiesPublicPartyButton: TODO Public Party Profile
YourPartiesDuplicatePartyButton: TODO Duplicate
YourPartiesCancelPartyButton: TODO Cancel
YourPartiesUnCancelPartyButton: TODO Un-Cancel
YourPartiesDeletePartyWarning: TODO Are you sure you want to delete this party? This cannot be undone.
YourPartiesDeletePartyButton: TODO Delete

# Party form
PartyFormTitleLabel: TODO Title
PartyFormDayLabel: TODO Day
PartyFormAddressLabel: TODO Address
PartyFormDescriptionLabel: TODO Description
PartyFormStartLabel: TODO Start
PartyFormHomepageLabel: TODO Website
PartyFormPriceLabel: TODO Price
PartyFormPriceHelp: TODO Make sure to write FREE if the party is free.
PartyFormPosterLabel: TODO Poster
PartyFormPosterChooseInstruction: TODO Choose a poster image
PartyFormPosterNoPoster: TODO No poster selected
PartyFormBackButton: TODO Back

# Submit Party
SubmitPartyTitle: TODO Submit Party
SubmitPartyButton: TODO Submit
SubmitPartySuccess: TODO Succesfully submitted party
SubmitPartyErrorUnverified: TODO Your account needs to verified before you can submit parties.
SubmitPartyErrorNoOrganiser: TODO You must set up an organiser profile in the account overview before you can submit a party.

# Edit Party
EditPartyTitle: TODO Submit Party
EditPartyButton: TODO Submit
EditPartySuccess: TODO Succesfully edited party
EditPartyPublicPartyProfile: TODO Public Party Profile
EditPartyDayHelp: TODO You can no longer edit the day for the party. If you were looking to do that, you can either cancel this party and organise another, or duplicate this party to re-organise it.
EditPartyErrorNoOrganiser: TODO You must set up an organiser profile in the account overview before you can edit a party.
EditPartyErrorNotYourParty: TODO This is not your party to edit.

# Duplicate Party
DuplicatePartyTitle: TODO Submit Party
DuplicatePartyButton: TODO Submit
DuplicatePartyErrorNoOrganiser: TODO You must set up an organiser profile in the account overview before you can duplicate a party.
DuplicatePartyErrorNotYourParty: TODO This is not your party to duplicate.

# Cancel party
CancelPartyErrorNotYourParty: TODO This is not your party to cancel.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: TODO This is not your party to un-cancel.

# Delete party
DeletePartyErrorNotYourParty: TODO This is not your party to delete.

# Pagination
PaginationPrevious: TODO Previous
PaginationNext: TODO Next

# Auto day
DayMoreThanAYearAgo: vor mehr als einem Jahr
Day11MonthsAgo: vor 11 Monaten
Day10MonthsAgo: vor 10 Monaten
Day9MonthsAgo: vor 9 Monaten
Day8MonthsAgo: vor 8 Monaten
Day7MonthsAgo: vor 7 Monaten
Day6MonthsAgo: vor 6 Monaten
Day5MonthsAgo: vor 5 Monaten
Day4MonthsAgo: vor 4 Monaten
Day3MonthsAgo: vor 3 Monaten
Day2MonthsAgo: vor 2 Monaten
Day1MonthAgo: vor einem Monat
Day4WeeksAgo: vor 4 Wochen
Day3WeeksAgo: vor 3 Wochen
Day2WeeksAgo: vor 2 Wochen
Day1WeekAgo: vor einer Woche
Day6DaysAgo: vor 6 Tagen
Day5DaysAgo: vor 5 Tagen
Day4DaysAgo: vor 4 Tagen
Day3DaysAgo: vor 3 Tagen
Day2DaysAgo: vorgestern
DayYesterday: gestern
DayToday: heute
DayTomorrow: morgen
DayIn2Days: übermorgen
DayIn3Days: In 3 Tagen
DayIn4Days: In 4 Tagen
DayIn5Days: In 5 Tagen
DayIn6Days: In 6 Tagen
DayIn1Week: In einer Woche
DayIn2Week: In 2 Wochen
DayIn3Week: In 3 Wochen
DayIn4Week: In 4 Wochen
DayIn1Month: In einem Monat
DayIn2Months: In 2 Monaten
DayIn3Months: In 3 Monaten
DayIn4Months: In 4 Monaten
DayIn5Months: In 5 Monaten
DayIn6Months: In 6 Monaten
DayIn7Months: In 7 Monaten
DayIn8Months: In 8 Monaten
DayIn9Months: In 9 Monaten
DayIn10Months: In 10 Monaten
DayIn11Months: In 11 Monaten
DayInMoreThanAYear: in mehr als einem Jahr

# Errors
NotFound: TODO Page not found
