# Logo
SalsaPartiesLogo: Salsa Parties Logo

# Home Page
HomeTitle: Salsa Parties Heute
HomeDescription: Wo kann ich tanzen gehen?
HomeSubtitleQuestion: Wo kann ich tanzen gehen?
HomeFormLocation: Mein Standort
HomeFormLocationUnable: Lokalisierung fehlgeschlagen.
HomeFormLocationNotSupported: Geolocation wird von Ihrem Browser nicht unterstützt.
HomeFormLocationInProgress: Lokalisieren…
HomeFormLocationDone: Lokalisiert
HomeFormSearch: Suche
HomeFormHelp: Drücken Sie die Suchtaste, um parties in ihrer Umgebung zu finden.

HomeExploreTitle: Erkunde die Welt des Sozial Dance!
HomeExplore: Erkunden

## Footer
FooterGeocodingAttribution: Geokodierung durch OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap Mitwirkende


# Navbar
NavFind: Party suchen
NavAccount: Konto
NavOrganiser: Veranstalterprofil
NavParties: Meine Partys
NavLanguage: Sprache
NavAdmin: Admin-Panel
NavSignUp: Registrieren
NavLogIn: Anmelden
NavLogOut: Admelden

# Search Results
SearchPartiesAroundAddress address@Text: Parties in der Nähe von #{address}
SearchPartiesAroundYourLocation: Parties in deiner Umgebung
SearchNoParties: Es wurden keine Parties gefunden.
SearchPosterAlt title@Text day@String: Poster für #{title} am #{day}.

SearchNavEarlier: Früher
SearchNavLater: Später

