# Translators
# s.ostermeier88@gmail.com

# Logo
Logo title@Text: #{title} Logo

# Home Page
HomeDescription title@Text: #{title}: Wo kann ich tanzen gehen? Finde heute Social Dance Partys. Egal ob du nach Salsa, Bachata, Kizomba, Mambo, Cha-Cha-Cha, Tango, Zouk, Swng, Kindy Hop oder einen anderen Tanz suchst, du findest sie hier.
HomeSubtitleQuestion: Wo kann ich tanzen gehen?
HomeFormSearch: Suche

# Advanced search
AdvancedSearchTitle: TODO Advanced Search
AdvancedSearchDescription: TODO Find exactly the social dance parties that you are looking for.
AdvancedSearchFormLocationLabel: TODO Location
AdvancedSearchFormDistanceLabel: TODO Distance
AdvancedSearchFormBeginLabel: Von
AdvancedSearchFormEndLabel: Bis
AdvancedSearchFormSubmit: Suchen

# Locate me button 
LocateMeLocation: Mein Standort
LocateMeUnable: Lokalisierung fehlgeschlagen.
LocateMeInProgress: Lokalisieren…
LocateMeDone: Lokalisiert
LocateMeHelpBefore: Drücken Sie auf 'Mein standort', um parties in ihrer Umgebung zu finden.
LocateMeHelpAfter: TODO Your current location will be used for the search unless you fill in another location above.
 
# Explore
ExploreTitle: Erkunde die Welt des Sozial Dance!
ExploreDescription: Social Dance gibt es auf der ganzen Welt, finde heraus, wohin du gehen kannst!
ExploreButton: Erkunden
ExploreUpcomingParties number@String: #{number} bevorstehenden Parties
ExploreSkylineAlt location@Text:  Nächtliche Skyline von #{location}

## Footer
FooterGeocodingAttribution: Geokodierung durch OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap Mitwirkende


# Navbar
NavFind: Parties suchen
NavSubmitParty: Party hinzufügen
NavAccount: Konto
NavOrganiser: Veranstalterprofil
NavParties: Meine Partys
NavLanguage: Sprache
NavAdmin: Admin-Panel
NavSignUp: Registrieren
NavLogIn: Anmelden
NavLogOut: Abmelden

# Form messages
InvalidLatitude lat@String: Ungültiger Breitengrat: #{lat}
InvalidLongitude lon@String: Ungültiger Längengrad: #{lon}
DistanceTooGreat distance@String: TODO Distance too great: #{distance} km
EndBeforeBegin: TODO The end date was before the begin date.
EndTooFarAhead: TODO Search date range too big.
AddressOrCoordinates: Geben Sie entweder eine Adresse oder Koordinate ein.

# Search Results
SearchTitleAroundYourLocationToday:  Social Dance Parties in deiner Umgebung heute
SearchTitleAroundYourLocationOnDay day@String:  Social Dance Parties in der Nähe am #{day}
SearchTitleAroundYourLocationFromTo begin@String end@String: TODO Social dance parties near your location between #{begin} and #{end}
SearchTitleAroundAddressToday address@Text:  Social Dance Parties in der Nähe von #{address} heute
SearchTitleAroundAddressOnDay address@Text day@String:  Social Dance Parties in der Nähe von #{address} am #{day}
SearchTitleAroundAddressFromTo address@Text begin@String end@String: TODO Social dance parties near #{address} between #{begin} and #{end}
SearchDescriptionAroundYourLocationToday:  Eine Liste von allen Social Dance Parties in deiner Umgebung heute
SearchDescriptionAroundYourLocationOnDay day@String:  Eine Liste von allen Social Dance Parties in der Nähe am #{day}
SearchDescriptionAroundYourLocationFromTo begin@String end@String: TODO A List of social dance parties near your location between #{begin} and #{end}
SearchDescriptionAroundAddressToday address@Text:  Eine Liste von allen Social Dance Parties in der Nähe von #{address} today
SearchDescriptionAroundAddressOnDay address@Text day@String:  Eine Liste von allen Social Dance Parties in der Nähe  von #{address} am #{day}
SearchDescriptionAroundAddressFromTo address@Text begin@String end@String: TODO A List of social dance parties near #{address} between #{begin} and #{end}
SearchPartiesAroundAddress address@Text: Social Dance Parties in der Nähe von #{address}
SearchPartiesAroundYourLocation: Social Dance Parties in deiner Umgebung
SearchNoParties: Es wurden keine Parties gefunden.
SearchPosterAlt title@Text day@String: Poster für #{title} am #{day}.
SearchNoResults: Wir haben noch keine Daten zu dieser Gegend.
SearchNoResultsHelp: Wir brauchen Ihre Hilfe, um mehr Daten über diese Gegend zu sammeln. Bitte nehmen Sie Kontakt mit den Partyorganisatoren auf und informieren Sie sie über diese Seite. Wenn Sie Partys in diesem Bereich organisieren, melden Sie sich bitte hier an und bewerben Sie Ihre Partys. 


SearchNavEarlier: Früher
SearchNavLater: Später


# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: ABGESAGT: #{title}
PartyDescription description@Text:  #{description}

PartyAddress address@Text: #{address}
PartyOrganiser name@Text: Veranstalter: #{name}
PartyOrganiserTitle organiserName@Text: Veranstalterprofil von #{organiserName}
PartyPrice price@Text: Preis: #{price}
PartyHomepage: Webseite
PartyHomepageTitle partyTitle@Text: Webseite von #{partyTitle}
PartyDownloadCalendarEvent: Kalendar-Event herunterladen
PartyDownloadCalendarEventTitle partyTitle@Text: Kalendar-Event herunterladen für #{partyTitle}
PartyAddToGoogleCalendar: Zu Google Calendar hinzufügen
PartyAddToGoogleCalendarTitle partyTitle@Text: #{partyTitle} zu Google Calendar hinzufügen

PartyDescriptionDay day@String: am #{day}
PartyDescriptionDateTime day@String start@String: am #{day} um #{start}
PartyDescriptionOrganiser name@Text: durch #{name}
PartyDescriptionAddress address@Text: Adresse: #{address}

ExternalEventCaution: Event via Websuche gefunden. Behandeln Sie diese Informationen mit Vorsicht. (Or: Angaben ohne Gewähr.)

# Organiser Page
OrganiserTitle name@Text:  Veranstalterprofil: #{name}
OrganiserHomepage: Webseite
OrganiserHomepageTitle name@Text: Webseite von #{name}
OrganiserDescription name@Text:  Veranstalterprofil von #{name}, und eine Liste seiner/ihrer bevorstehenden Social Dance Parties 
OrganiserName name@Text: Veranstalter/in: #{name}
OrganiserUpcomingParties: Bevorstehende Parties
OrganiserNoUpcomingParties: Keine bevorstehenden Parties

# Poster
PosterAltFull title@Text day@String organiser@Text: Bild für #{title} am #{day} organisiert durch #{organiser}
PosterAltTitle title@Text day@String: Bild für #{title} am #{day}
PosterAltSchedule title@Text recurrenceDescription@Text organiser@Text: Bild für #{title}, #{recurrenceDescription} durch #{organiser}

# Registration
RegistrationTitle: Registrierung
RegistrationDescription: Erstellen Sie einen Account
RegistrationEmailAddressLabel: Email-Adresse
RegistrationPassphraseLabel: Passwort-Satz
RegistrationConfirmPassphraseLabel: Passwort-Satz bestätigen
RegistrationSignUpButton:  Registrieren
RegistrationLogInButton:  Anmelden
RegistrationErrorAccountAlreadyExists: Es besteht bereits ein Account mit diesem Benutzernamen

# Anmelden
LoginTitle: Anmelden
LoginDescription: Melde dich an
LoginEmailAddressLabel: Email-Adresse
LoginPassphraseLabel: Passwort-Satz
LoginLogInButton: Anmelden
LoginSignUpButton: Registrieren

# Bestätigungs-Email
VerificationEmailSubject title@Text: #{title} Email bestätigung
VerificationEmailTitle title@Text: #{title} Registrierung
VerificationEmailTextCTA: Bitte bestätigen Sie Ihre Email-Adresse, indem sie folgendem Link folgen:
VerificationEmailHtmlCTA: Bitte bestätigen Sie Ihre Email-Adresse, indem Sie den unterstehenden Link anklicken.
VerificationEmailButton: Bestätigen Sie Ihre Email-Adresse.
VerificationEmailInvitation: Wir hoffen, Sie bald zu treffen.
VerificationEmailExplanation title@Text: Sie haben dieses Mail erhalten, weil Sie versucht haben, sich bei #{title} zu registrieren. 

VerificationEmailFailure:  Senden des Bestätigungs-Emails fehlgeschlagen 
VerificationErrorAlreadyVerified:  Dieses Konto ist bereits bestätigt.

# Account Page
AccountOverviewTitle:  Konto
AccountEmailAddress emailAddress@Text:  Email-Addresse: #{emailAddress}
AccountVerificationTitle:  Kontobestätigung
AccountVerificationWarning:  Ihr Konto ist noch nicht bestätigt. Sie können noch keine Parties erstellten. 
AccountVerificationCheckEmail:  Bitte überprüfen Sie Ihren Posteingang auf eine Bestätigungs-E-Mail.
AccountVerificationCheckEmailDisclaimer:  Wenn Ihre Bestätigungs-E-Mail noch nicht angekommen ist, überprüfen Sie bitte Ihren Spam-Ordner. Wir tun unser Bestes, um zu verhindern, dass E-Mails im Spam landen. Dies kann manchmal scheitert. Wenn Sie immer noch keine Bestätigungs-E-Mail finden, wenden Sie sich bitte an den Administrator.
AccountVerificationResendButton:  Bestätigungs-Mail erneut senden
AccountDangerZoneTitle:  Gefahrenzone
AccountDeleteButton:  Konto löschen
AccountDeleteWarning:  Sind Sie sicher, dass sie Ihr Konto löschen wollen? Das kann nicht rückgängig gemacht werden.

# Organiser Profile
OrganiserProfileTitle:  Veranstalterprofil
OrganiserDisplayNameLabel:  Anzeigename
OrganiserHomepageLabel: Website
OrganiserConsentReminderLabel: Ich möchte daran erinnert werden, Parties zu erstellen.
OrganiserConsentReminderHelp: Wir versenden nicht mehr als eine Erinnerungs-E-Mail pro Woche. Sie können dies jederzeit deaktivieren.
OrganiserSubmitButton:  Erstellen
OrganiserViewPublicProfileButton:  Öffentliches Veranstalterprofil anzeigen
OrganiserSaveSuccess: Veranstalterprofil erfolgreich gespeichert

# Submit
SubmitTitle: Ihre party hinzufügen
SubmitSingleParty: Einzelne Party
SubmitRecurringParty: Wiederkehrende Party
SubmitSinglePartyExplanation1: Eine einzelne Party findet nur einmal an einem bestimmten Datum statt. 
SubmitSinglePartyExplanation2: Sie können die Party später noch bearbeiten, absagen oder löschen.
SubmitRecurringPartyExplanation1: Eine wiederkehrende Party findet mehrmals statt, zum Beispiel jeden Freitag. 
SubmitRecurringPartyExplanation2: Wenn Sie eine wiederkehrende Party planen, generiert die Site Partys in der Zukunft. 
SubmitRecurringPartyExplanation3: Wenn Sie eine wiederkehrende Party bearbeiten, werden alle von ihr generierten zukünftigen Partys automatisch bearbeitet. 
SubmitRecurringPartyExplanation4: Wenn Sie eine wiederkehrende Party löschen, werden alle zukünftigen Partys im Zeitplan abgesagt und es werden keine zukünftigen generiert. 

# Your parties
YourPartiesTitle: Ihre Parties
YourPartiesPartiesSubtitle: Parties
YourPartiesSchedulesSubtitle: Wiederkehrende Parties
YourPartiesSubmitButton: Party erstellen
YourPartiesNoParties: Sie haben noch keine Parties erstellt.
YourPartiesEditPartyButton: Bearbeiten
YourPartiesEditScheduleButton: Bearbeiten
YourPartiesPublicPartyButton: Öffentliches Party-Profil
YourPartiesDuplicatePartyButton: Duplizieren
YourPartiesCancelPartyButton: Absagen
YourPartiesUnCancelPartyButton: Rückgängig machen
YourPartiesDeletePartyWarning: Sind Sie sicher, dass Sie diese Party löschen wollen? Das kann nicht rückgängig gemacht werden. 
YourPartiesDeletePartyButton: Löschen

# Party form
PartyFormTitleLabel:  Titel
PartyFormDayLabel:  Tag
PartyFormAddressLabel:  Adresse
PartyFormDescriptionLabel:  Beschreibung
PartyFormStartLabel:  Start
PartyFormHomepageLabel:  Webseite
PartyFormPriceLabel:  Preis
PartyFormPriceHelp:  Stellen Sie sicher, dass Sie KOSTENLOS schreiben, wenn die Party kostenlos ist.
PartyFormPosterLabel:  Bild
PartyFormPosterChooseInstruction:  Bild auswählen
PartyFormPosterNoPoster:  Kein Bild ausgewählt
PartyFormBackButton:  Zurück

# Account Party
AccountPartyErrorNotYourParty: Dies ist nicht ihre Party.

# Submit Party
SubmitPartyTitle:  Party erstellen
SubmitPartyButton:  Speichern
SubmitPartySuccess:  Party erfolgreich erstellt
SubmitPartyErrorUnverified:  Ihr Konto muss zuerst bestätigt werden, bevor Sie Parties erstellen können.
SubmitPartyErrorNoOrganiser:  Bevor Sie eine Party erstellen können, müssen Sie in der Kontoübersicht ein Veranstalterprofil anlegen.

# Party bearbeiten
EditPartyTitle:  Party bearbeiten 
EditPartyButton:  Speichern
EditPartySuccess:  Erfolgreich bearbeitete Party
EditPartyPublicPartyProfile:  Öffentliches Party-Profil
EditPartyDayHelp:  Sie können den Tag für die Party nicht mehr bearbeiten. Wenn Sie dies wünschen, können Sie diese Party entweder absagen und eine andere organisieren oder diese Party duplizieren, um sie neu zu organisieren.
EditPartyErrorNotYourParty: Diese Party können Sie nicht bearbeiten, da es nicht Ihre Party ist.

# Duplicate party
DuplicatePartyTitle: Party duplizieren
DuplicatePartyButton: Speichern

# Cancel party
CancelPartyErrorNotYourParty: Diese Party können sie nicht absagen, da es nicht Ihre Party ist.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: Die Absage dieser Party können Sie nicht Rückgängig machen, da es nicht Ihre Party ist.

# Delete party
DeletePartyErrorNotYourParty: Sie können diese Party nicht löschen, da es nicht Ihre Party ist.


# Schedule Form
ScheduleFormTitleLabel: Partyplan erstellen
ScheduleFormRecurrenceLabel: Wiederkehr
ScheduleFormAddressLabel:  Adresse
ScheduleFormDescriptionLabel: Beschreibung
ScheduleFormStartLabel: Start
ScheduleFormHomepageLabel: Webseite
ScheduleFormPriceLabel: Preis
ScheduleFormPriceHelp: Stellen Sie sicher, dass Sie KOSTENLOS schreiben, wenn die Party kostenlos ist.
ScheduleFormPosterLabel: Bild
ScheduleFormPosterChooseInstruction: Bild auswählen
ScheduleFormPosterNoPoster: Kein Bild ausgewählt
ScheduleFormBackButton: Zurück

# Account Schedule
AccountScheduleParties: Generierte Parties

## Recurrence
RecurrenceWeeklyType: wöchentlich
RecurrenceWeeklyDescription weekday@String: jede Woche am #{weekday}

# Submit Schedule
SubmitScheduleTitle: Partyplan erstellen
SubmitScheduleButton: Erstellen
SubmitScheduleSuccess: Partyplan erfolgreich erstellt
SubmitScheduleErrorUnverified: Ihr Konto muss zuerst bestätigt werden, bevor Sie Partypläne erstellen können. 
SubmitScheduleErrorNoOrganiser: Bevor Sie ein Partyplan erstellen können, müssen Sie in der Kontoübersicht ein Veranstalterprofil anlegen.

# Edit Schedule
EditScheduleTitle: Partyplan bearbeiten
EditScheduleButton: Speichern
EditScheduleSuccess: Partyplan erfolgreich gespeichert
EditScheduleErrorNotYourSchedule: Diese Party können Sie nicht bearbeiten, da es nicht Ihre Party ist.

# Your schedules
YourSchedulesTitle: Ihre Partypläne
YourSchedulesSubmitButton: Partyplan erstellen
YourSchedulesNoSchedules: Sie haben noch keine Partypläne erstellt.
YourSchedulesEditScheduleButton: Bearbeiten
YourSchedulesDeleteScheduleWarning: Sind Sie sicher, dass Sie diese Party löschen wollen? Das kann nicht rückgängig gemacht werden. Bereits geplante Partys werden nicht gelöscht.
YourSchedulesDeleteScheduleButton: löshen
ScheduleTitle title@Text: #{title}

# Delete schedule
DeleteScheduleErrorNotYourSchedule: Sie können diesen Partyplan nicht löschen, da es nicht Ihren Partyplan ist.


# Unsubscribe Reminder
UnsubReminderTitle: Abgemeldet
UnsubReminderDescription: Sie erhalten keine Erinnerungs-E-Mails mehr. 

# Google Maps
GoogleMapAlt location@Text: Karte der Umgebung von #{location}

# Pagination
PaginationPrevious:  Früher
PaginationNext:  Später

# Auto day
DayMoreThanAYearAgo: vor mehr als einem Jahr
Day11MonthsAgo: vor 11 Monaten
Day10MonthsAgo: vor 10 Monaten
Day9MonthsAgo: vor 9 Monaten
Day8MonthsAgo: vor 8 Monaten
Day7MonthsAgo: vor 7 Monaten
Day6MonthsAgo: vor 6 Monaten
Day5MonthsAgo: vor 5 Monaten
Day4MonthsAgo: vor 4 Monaten
Day3MonthsAgo: vor 3 Monaten
Day2MonthsAgo: vor 2 Monaten
Day1MonthAgo: vor einem Monat
Day4WeeksAgo: vor 4 Wochen
Day3WeeksAgo: vor 3 Wochen
Day2WeeksAgo: vor 2 Wochen
Day1WeekAgo: vor einer Woche
Day6DaysAgo: vor 6 Tagen
Day5DaysAgo: vor 5 Tagen
Day4DaysAgo: vor 4 Tagen
Day3DaysAgo: vor 3 Tagen
Day2DaysAgo: vorgestern
DayYesterday: gestern
DayToday: heute
DayTomorrow: morgen
DayIn2Days: übermorgen
DayIn3Days: In 3 Tagen
DayIn4Days: In 4 Tagen
DayIn5Days: In 5 Tagen
DayIn6Days: In 6 Tagen
DayIn1Week: In einer Woche
DayIn2Week: In 2 Wochen
DayIn3Week: In 3 Wochen
DayIn4Week: In 4 Wochen
DayIn1Month: In einem Monat
DayIn2Months: In 2 Monaten
DayIn3Months: In 3 Monaten
DayIn4Months: In 4 Monaten
DayIn5Months: In 5 Monaten
DayIn6Months: In 6 Monaten
DayIn7Months: In 7 Monaten
DayIn8Months: In 8 Monaten
DayIn9Months: In 9 Monaten
DayIn10Months: In 10 Monaten
DayIn11Months: In 11 Monaten
DayInMoreThanAYear: in mehr als einem Jahr

# Errors
NotFound: Seite nicht gefunden 
