# Logo
SalsaPartiesLogo: Salsa Parties Logo

# Home Page
HomeTitle: Salsa Parties Today
HomeDescription: Where can I dance?
HomeSubtitleQuestion: Where can I dance?
HomeFormLocation: My location
HomeFormLocationUnable: Unable to retrieve your location.
HomeFormLocationNotSupported: Geolocation is not supported by your browser.
HomeFormLocationInProgress: Locating…
HomeFormLocationDone: Located
HomeFormSearch: Search
HomeFormHelp: Press the search button to find parties around your current location.

HomeExploreTitle: Explore the world of social dance!
HomeExplore: Explore

## Footer
FooterGeocodingAttribution: Geocoding by OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap contributors

# Navbar
NavFind: Find a party
NavAccount: Account
NavOrganiser: Organiser profile
NavParties: My parties
NavLanguage: Language
NavAdmin: Admin panel
NavSignUp: Sign up
NavLogIn: Log in
NavLogOut: Log out

# Search Results
SearchPartiesAroundAddress address@Text: Parties near #{address}
SearchPartiesAroundYourLocation: Parties near your location
SearchNoParties: No parties found for this day.
SearchPosterAlt title@Text day@String: Poster for #{title} on #{day}.

SearchNavEarlier: Earlier
SearchNavLater: Later

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: CANCELLED: #{title}

PartyAddress address@Text: Address: #{address}
PartyOrganiser name@Text: Organiser: #{name}
PartyPrice price@Text: Price: #{price}
PartyHomepage: Website
PartyDownloadCalendarEvent: Download Calendar Event
PartyAddToGoogleCalendar: Add to Google Calendar

ExternalEventCaution: Event found via web search, treat this information with caution.

# Organiser Page
OrganiserName name@Text: Organiser: #{name}
OrganiserUpcomingParties: Upcoming parties
OrganiserNoUpcomingParties: No upcoming parties
