# Logo
SalsaPartiesLogo: Salsa Parties Logo

# Home Page
HomeTitle: Salsa Parties Today
HomeDescription: Where can I dance?
HomeSubtitleQuestion: Where can I dance?
HomeFormLocation: My location
HomeFormLocationUnable: Unable to retrieve your location.
HomeFormLocationNotSupported: Geolocation is not supported by your browser.
HomeFormLocationInProgress: Locating…
HomeFormLocationDone: Located
HomeFormSearch: Search
HomeFormHelp: Press the search button to find parties around your current location.

HomeExploreTitle: Explore the world of social dance!
HomeExplore: Explore

## Footer
FooterGeocodingAttribution: Geocoding by OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap contributors

# Navbar
NavFind: Find a party
NavAccount: Account
NavOrganiser: Organiser Profile
NavParties: My Parties
NavLanguage: Language
NavAdmin: Admin Panel
NavSignUp: Sign up
NavLogIn: Log in
NavLogOut: Log out

