# Logo
SalsaPartiesLogo: Salsa Parties Logo

# Home Page
HomeTitle: Salsa Parties Today
HomeDescription: Where can I dance?
HomeSubtitleQuestion: Where can I dance?
HomeFormLocation: My location
HomeFormLocationUnable: Unable to retrieve your location.
HomeFormLocationNotSupported: Geolocation is not supported by your browser.
HomeFormLocationInProgress: Locating…
HomeFormLocationDone: Located
HomeFormSearch: Search
HomeFormHelp: Press the search button to find parties around your current location.

# Explore
ExploreTitle: Explore the world of social dance!
ExploreDescription: Social dance exists all over the world, find out where to go!
ExploreButton: Explore
ExploreSkylineAlt location@Text: Night-time skyline of #{location}
ExploreUpcomingParties number@String: #{number} upcoming parties

## Footer
FooterGeocodingAttribution: Geocoding by OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap contributors

# Navbar
NavFind: Find a party
NavSubmitParty: Advertise your party here
NavAccount: Account
NavOrganiser: Organiser profile
NavParties: My parties
NavSchedules: My party schedules
NavLanguage: Language
NavAdmin: Admin panel
NavSignUp: Sign up
NavLogIn: Log in
NavLogOut: Log out

# Search Results
SearchTitleAroundYourLocationToday: Social dance parties near your location today
SearchTitleAroundYourLocationOnDay day@String: Social dance parties near your location on #{day}
SearchTitleAroundAddressToday address@Text: Social dance parties near #{address} today
SearchTitleAroundAddressOnDay address@Text day@String: Social dance parties near #{address} on #{day}
SearchDescriptionAroundYourLocationToday: A List of social dance parties near your location oday
SearchDescriptionAroundYourLocationOnDay day@String: A List of social dance parties near your location on #{day}
SearchDescriptionAroundAddressToday address@Text: A List of social dance parties near #{address} today
SearchDescriptionAroundAddressOnDay address@Text day@String: A List of social dance parties near #{address} on #{day}
SearchPartiesAroundAddress address@Text: Social dance parties near #{address}
SearchPartiesAroundYourLocation: Social dance parties near your location
SearchNoParties: No parties found for this day.
SearchPosterAlt title@Text day@String: Poster for #{title} on #{day}.
SearchNoResults: We do not have any data about this area yet.
SearchNoResultsHelp: We need your help to gather more data about this area. Please get in touch with party organisers and tell them about this page. If you organise parties in this area, please sign up and advertise your parties here for free.

SearchNavEarlier: Earlier
SearchNavLater: Later

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: CANCELLED: #{title}
PartyDescription description@Text: #{description}
PartyWithoutDescription: Party without description

PartyAddress address@Text: Address: #{address}
PartyOrganiser name@Text: Organiser: #{name}
PartyPrice price@Text: Price: #{price}
PartyHomepage: Website
PartyDownloadCalendarEvent: Download Calendar Event
PartyAddToGoogleCalendar: Add to Google Calendar

ExternalEventCaution: Event found via web search, treat this information with caution.

# Organiser Page
OrganiserTitle name@Text: Organiser profile: #{name}
OrganiserDescription name@Text: The organiser profile of #{name}, and a list of their upcoming social dance parties
OrganiserName name@Text: Organiser: #{name}
OrganiserUpcomingParties: Upcoming parties
OrganiserNoUpcomingParties: No upcoming parties

# Poster
PosterAltFull title@Text day@String organiser@Text: Poster for #{title} on #{day} by #{organiser}
PosterAltTitle title@Text day@String: Poster for #{title} on #{day}

# Registration
RegistrationTitle: Salsa Parties Today: Registration
RegistrationDescription: Register an account at Salsa Parties Today
RegistrationEmailAddressLabel: Email Address
RegistrationPassphraseLabel: Passphrase
RegistrationConfirmPassphraseLabel: Confirm Passphrase
RegistrationSignUpButton: Sign up
RegistrationLogInButton: Log in
RegistrationErrorAccountAlreadyExists: An account with this email address already exists.

# Login
LoginTitle: Salsa Parties Today: Login
LoginDescription: Log into your account at Salsa Parties Today
LoginEmailAddressLabel: Email Address
LoginPassphraseLabel: Passphrase
LoginLogInButton: Log in
LoginSignUpButton: Sign up

# Verification Email
VerificationEmailSubject: Salsa Party Today Email Verification
VerificationEmailTitle: Salsa Party Today Registration
VerificationEmailTextCTA: Please verify your email address by following this link:
VerificationEmailHtmlCTA: Please verify your email address by clicking the link below.
VerificationEmailButton: Verify Email
VerificationEmailInvitation: We hope to see you soon.
VerificationEmailExplanation: You got this email because you tried to register at Salsa Parties Today

VerificationEmailFailure: Failed to send verification email.
VerificationErrorAlreadyVerified: This account is already verified.


# Account Page
AccountOverviewTitle: Account
AccountEmailAddress emailAddress@Text: Email Address: #{emailAddress}
AccountVerificationTitle: Account Verification
AccountVerificationWarning: Your account is not verified yet. You will not be able to submit parties.
AccountVerificationCheckEmail: Please check your email inbox for a verification email.
AccountVerificationCheckEmailDisclaimer: If your verification email has not arrived yet, please make sure to check your spam folder. We do our best to prevent emails from ending up in spam but fail sometimes. If you still do not find a verification email, please contact the site administrators.
AccountVerificationResendButton: Resend Verification Email
AccountDangerZoneTitle: Danger Zone
AccountDeleteButton: Delete Account
AccountDeleteWarning: Are you sure you want to delete your account? This cannot be undone.

# Organiser Profile
OrganiserProfileTitle: Organiser Profile
OrganiserDisplayNameLabel: Display Name
OrganiserConsentReminderLabel: I want to be reminded to submit parties.
OrganiserConsentReminderHelp: We will send no more than one reminder email per week. You can turn this off at any time.
OrganiserSubmitButton: Submit
OrganiserViewPublicProfileButton: View Public Profile
OrganiserSaveSuccess: Succesfully saved organiser profile

# Your parties
YourPartiesTitle: Your parties
YourPartiesSubmitButton: Submit party
YourPartiesNoParties: You have not submitted any parties yet.
YourPartiesEditPartyButton: Edit
YourPartiesPublicPartyButton: Public Party Profile
YourPartiesDuplicatePartyButton: Duplicate
YourPartiesCancelPartyButton: Cancel
YourPartiesUnCancelPartyButton: Un-Cancel
YourPartiesDeletePartyWarning: Are you sure you want to delete this party? This cannot be undone.
YourPartiesDeletePartyButton: Delete

# Party form
PartyFormTitleLabel: Title
PartyFormDayLabel: Day
PartyFormAddressLabel: Address
PartyFormDescriptionLabel: Description
PartyFormStartLabel: Start
PartyFormHomepageLabel: Website
PartyFormPriceLabel: Price
PartyFormPriceHelp: Make sure to write FREE if the party is free.
PartyFormPosterLabel: Poster
PartyFormPosterChooseInstruction: Choose a poster image
PartyFormPosterNoPoster: No poster selected
PartyFormBackButton: Back

# Submit Party
SubmitPartyTitle: Submit Party
SubmitPartyButton: Submit
SubmitPartySuccess: Succesfully submitted party
SubmitPartyErrorUnverified: Your account needs to verified before you can submit parties.
SubmitPartyErrorNoOrganiser: You must set up an organiser profile in the account overview before you can submit a party.

# Edit Party
EditPartyTitle: Submit Party
EditPartyButton: Submit
EditPartySuccess: Succesfully edited party
EditPartyPublicPartyProfile: Public Party Profile
EditPartyDayHelp: You can no longer edit the day for the party. If you were looking to do that, you can either cancel this party and organise another, or duplicate this party to re-organise it.
EditPartyErrorNoOrganiser: You must set up an organiser profile in the account overview before you can edit a party.
EditPartyErrorNotYourParty: This is not your party to edit.

# Duplicate Party
DuplicatePartyTitle: Submit Party
DuplicatePartyButton: Submit
DuplicatePartyErrorNoOrganiser: You must set up an organiser profile in the account overview before you can duplicate a party.
DuplicatePartyErrorNotYourParty: This is not your party to duplicate.

# Schedule Form
ScheduleFormTitleLabel: Title
ScheduleFormRecurrenceLabel: Recurrence
ScheduleFormAddressLabel: Address
ScheduleFormDescriptionLabel: Description
ScheduleFormStartLabel: Start
ScheduleFormHomepageLabel: Website
ScheduleFormPriceLabel: Price
ScheduleFormPriceHelp: Make sure to write FREE if the party is free.
ScheduleFormPosterLabel: Poster
ScheduleFormPosterChooseInstruction: Choose a poster image
ScheduleFormPosterNoPoster: No poster selected
ScheduleFormBackButton: Back

## Recurrence
ScheduleFormRecurrenceWeeklyType: Weekly
ScheduleFormRecurrenceWeeklyDescription weekday@String: Every week on: #{weekday}

# Submit Schedule
SubmitScheduleTitle: Submit Schedule
SubmitScheduleButton: Submit
SubmitScheduleSuccess: Succesfully submitted party
SubmitScheduleErrorUnverified: Your account needs to verified before you can submit parties.
SubmitScheduleErrorNoOrganiser: You must set up an organiser profile in the account overview before you can submit a party.

# Edit Schedule
EditScheduleTitle: Submit Schedule
EditScheduleButton: Submit
EditScheduleSuccess: Succesfully edited party
EditScheduleDayHelp: You can no longer edit the day for the party. If you were looking to do that, you can either cancel this party and organise another, or duplicate this party to re-organise it.
EditScheduleErrorNoOrganiser: You must set up an organiser profile in the account overview before you can edit a party.
EditScheduleErrorNotYourSchedule: This is not your party to edit.

# Your schedules
YourSchedulesTitle: Your party schedules
YourSchedulesSubmitButton: Submit a party schedule
YourSchedulesNoSchedules: You have not submitted any party schedules yet.

# Cancel party
CancelPartyErrorNotYourParty: This is not your party to cancel.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: This is not your party to un-cancel.

# Delete party
DeletePartyErrorNotYourParty: This is not your party to delete.

# Unsubscribe Reminder 
UnsubReminderTitle: Unsubscribed from reminder emails
UnsubReminderDescription: You have succesfully unsubscribed from reminder emails and revoked consent to receive any further reminder emails.


# Pagination
PaginationPrevious: Previous
PaginationNext: Next

# Auto day
DayMoreThanAYearAgo: more than a year ago
Day11MonthsAgo: 11 months ago
Day10MonthsAgo: 10 months ago
Day9MonthsAgo: 9 months ago
Day8MonthsAgo: 8 months ago
Day7MonthsAgo: 7 months ago
Day6MonthsAgo: 6 months ago
Day5MonthsAgo: 5 months ago
Day4MonthsAgo: 4 months ago
Day3MonthsAgo: 3 months ago
Day2MonthsAgo: 2 months ago
Day1MonthAgo: a month ago
Day4WeeksAgo: 4 weeks ago
Day3WeeksAgo: 3 weeks ago
Day2WeeksAgo: 2 weeks ago
Day1WeekAgo: a week ago
Day6DaysAgo: 6 days ago
Day5DaysAgo: 5 days ago
Day4DaysAgo: 4 days ago
Day3DaysAgo: 3 days ago
Day2DaysAgo: 2 days ago
DayYesterday: yesterday
DayToday: today
DayTomorrow: tomorrow
DayIn2Days: In 2 days
DayIn3Days: In 3 days
DayIn4Days: In 4 days
DayIn5Days: In 5 days
DayIn6Days: In 6 days
DayIn1Week: In a week
DayIn2Week: In 2 weeks
DayIn3Week: In 3 weeks
DayIn4Week: In 4 weeks
DayIn1Month: In a month
DayIn2Months: In 2 months
DayIn3Months: In 3 months
DayIn4Months: In 4 months
DayIn5Months: In 5 months
DayIn6Months: In 6 months
DayIn7Months: In 7 months
DayIn8Months: In 8 months
DayIn9Months: In 9 months
DayIn10Months: In 10 months
DayIn11Months: In 11 months
DayInMoreThanAYear: more than a year from now

# Errors
NotFound: Page not found


