


# Logo
Logo title@Text: #{title} Logo

# Home Page
HomeDescription title@Text: #{title}: ¿Dónde puedo bailar? Encuentra fiestas baile social hoy, ya sea que estés buscando Salsa, Bachata, Kizomba, Mambo, Cha-Cha-Cha, Tango, Zouk, Swing, Lindy Hop u otro baile, puedes encontrarlo aquí.
HomeSubtitleQuestion: ¿Dónde puedo bailar?
HomeFormSearch: Buscar
HomeAdvancedLabel: Avanzada

# Advanced search
AdvancedSearchTitle: Búsqueda Avanzada
AdvancedSearchDescription: Encuentra exactamente las fiestas de baile social que estás buscando.
AdvancedSearchFormLocationLabel: Ubicación
AdvancedSearchFormDistanceLabel: Distancia
AdvancedSearchFormBeginLabel: Desde
AdvancedSearchFormEndLabel: Hasta
AdvancedSearchFormSubmit: Buscar

# Locate me button
LocateMePlaceholder: Introduce la ubicación
LocateMeLocation: Mi ubicación
LocateMeUnable: No se puede encontrar tu ubicación.
LocateMeInProgress: Localizando…
LocateMeDone: Localizado
LocateMeHelpBefore: Presiona el botón 'Mi ubicación' para usar tu ubicación actual.
LocateMeHelpAfter: Su ubicación actual se utilizará para la búsqueda a menos que complete otra ubicación arriba.

# Explore
ExploreTitle: ¡Explora el mundo del baile social!
ExploreDescription: El baile social existe en todo el mundo, ¡descubre a dónde ir!
ExploreButton: Explorar
ExploreUpcomingParties number@String: #{number} próximas fiestas
ExploreSkylineAlt location@Text: Horizonte nocturno de #{location}

## Footer
FooterGeocodingAttribution: Geocodificación por OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © Colaboradores de OpenStreetMap

# Navbar
NavFind: Encontrar fiestas
NavSubmitParty: Agregar fiesta
NavAccount: Cuenta
NavOrganiser: Perfil de organizador
NavParties: Mis fiestas
NavLanguage: Idioma
NavAdmin: Panel de administrador
NavSignUp: Inscribirse
NavLogIn: Iniciar sesión
NavLogOut: Cerrar sesión

# Form messages
InvalidLatitude lat@String: Latitud no válida: #{lat}
InvalidLongitude lon@String: Longitud no válida: #{lon}
DistanceTooGreat distance@String: Distancia demasiado grande: #{distance} km
EndBeforeBegin: La fecha de finalización era anterior a la fecha de inicio.
EndTooFarAhead: Rango de fechas de búsqueda demasiado grande.
AddressOrCoordinates: Debe proporcionar una dirección o coordenadas.

# Search Results
SearchTitleAroundYourLocationToday: Fiestas de baile social cerca de su ubicación hoy
SearchTitleAroundYourLocationOnDay day@String: Fiestas de baile social cerca de tu ubicación el #{day}
SearchTitleAroundYourLocationFromTo begin@String end@String: Fiestas de baile social cerca de tu ubicación entre el #{begin} y el #{end}
SearchTitleAroundAddressToday address@Text: Fiestas de baile social cerca de #{address} hoy
SearchTitleAroundAddressOnDay address@Text day@String: Fiestas de baile social cerca de #{address} el #{day}
SearchTitleAroundAddressFromTo address@Text begin@String end@String: Fiestas de baile social cerca de #{address} entre el #{begin} y el #{end}
SearchDescriptionAroundYourLocationToday: Una lista de fiestas de baile social cerca de tu ubicación hoy
SearchDescriptionAroundYourLocationOnDay day@String: Una lista de fiestas de baile social cerca de tu ubicación el #{day}
SearchDescriptionAroundYourLocationFromTo begin@String end@String: Una lista de fiestas de baile social cerca de tu ubicación entre el #{begin} y el #{end}
SearchDescriptionAroundAddressToday address@Text: Una lista de fiestas de baile social cerca de #{address} hoy
SearchDescriptionAroundAddressOnDay address@Text day@String: Una lista de fiestas de baile social cerca de #{address} el #{day}
SearchDescriptionAroundAddressFromTo address@Text begin@String end@String: Una lista de fiestas de baile social cerca de #{address} entre el #{begin} y el #{end}
SearchPartiesAroundAddress address@Text: Fiestas de baile social cerca de #{address}
SearchPartiesAroundYourLocation: Fiestas de baile social cerca de tu ubicación
SearchNoParties: No se encontraron fiestas para este día.
SearchPosterAlt title@Text day@String: Póster para #{title} el #{day}.
SearchNoResults: Aún no tenemos datos sobre esta zona.
SearchNoResultsHelp: Necesitamos tu ayuda para recopilar más datos sobre esta área. Ponte en contacto con organizadores de fiestas y cuéntales sobre esta página. Si organizas fiestas en esta área, regístrate y anuncia tus fiestas aquí de forma gratuita.

SearchNavEarlier: Antes
SearchNavLater: Después

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: CANCELADA: #{title}
PartyDescription description@Text: #{description}

PartyAddress address@Text: #{address}
PartyOrganiser name@Text: Organizador: #{name}
PartyOrganiserTitle organiserName@Text: Perfil de organizador de #{organiserName}
PartyPrice price@Text: Precio: #{price}
PartyHomepage: Sitio web
PartyHomepageTitle partyTitle@Text: Página principal de #{partyTitle}
PartyDownloadCalendarEvent: Descargar calendario de eventos
PartyDownloadCalendarEventTitle partyTitle@Text: Descargar calendario de eventos para #{partyTitle}
PartyAddToGoogleCalendar: Agregar al calendario de Google
PartyAddToGoogleCalendarTitle partyTitle@Text: Agregar #{partyTitle} al calendario de Google

PartyDescriptionDay day@String: el #{day}
PartyDescriptionDateTime day@String start@String: el #{day} a la(s) #{start}
PartyDescriptionOrganiser name@Text: por #{name}
PartyDescriptionAddress address@Text: dirección: #{address}

ExternalEventCaution: Evento encontrado a través de la web, trate esta información con precaución.

# Organiser Page
OrganiserTitle name@Text: Perfil de organizador: #{name}
OrganiserHomepage: Página principal
OrganiserHomepageTitle name@Text: Página principal de #{name}
OrganiserDescription name@Text: El perfil de organizador de #{name}, y una lista de sus próximas fiestas de baile social
OrganiserName name@Text: Organizador: #{name}
OrganiserUpcomingParties: Próximas fiestas
OrganiserNoUpcomingParties: No hay próximas fiestas
OrganiserCalendarTitle: URL del calendario
OrganiserCalendarExplanation: Añade todos estos eventos a tu calendario automáticamente suscribiéndote a través de este enlace:

# Poster
PosterAltFull title@Text day@String organiser@Text: Póster para #{title} el #{day} por #{organiser}
PosterAltTitle title@Text day@String: Póster para #{title} el #{day}
PosterAltSchedule title@Text recurrenceDescription@Text organiser@Text: Póster para #{title}, #{recurrenceDescription} por #{organiser}

# Registration
RegistrationTitle: Registro
RegistrationDescription: Registrar una cuenta
RegistrationEmailAddressLabel: Dirección de correo electrónico
RegistrationPassphraseLabel: Contraseña
RegistrationConfirmPassphraseLabel: Confirmar contraseña
RegistrationSignUpButton: Inscribirse
RegistrationLogInButton: Iniciar sesión
RegistrationErrorAccountAlreadyExists: Ya existe una cuenta con esta dirección de correo electrónico.

# Login
LoginTitle: Acceso
LoginDescription: Ingrese a su cuenta
LoginEmailAddressLabel: Dirección de correo electrónico
LoginPassphraseLabel: Contraseña
LoginLogInButton: Iniciar sesión
LoginSignUpButton: Inscribirse

# Verification Email
VerificationEmailSubject title@Text: #{title} Verificación de email
VerificationEmailTitle title@Text: #{title} Registro
VerificationEmailTextCTA: Verifique su dirección de correo electrónico siguiendo este enlace:
VerificationEmailHtmlCTA: Verifique su dirección de correo electrónico haciendo click en el enlace a continuación.
VerificationEmailButton: Verificar correo electrónico
VerificationEmailInvitation: Esperamos verte pronto.
VerificationEmailExplanation title@Text: Recibiste este correo electrónico porque intentaste registrarte en #{title}
VerificationEmailFailure: No se pudo enviar el correo electrónico de verificación.
VerificationErrorAlreadyVerified: Esta cuenta ya está verificada.

# Account Page
AccountOverviewTitle: Cuenta
AccountEmailAddress emailAddress@Text: Dirección de correo electrónico: #{emailAddress}
AccountVerificationTitle: Verificación de la cuenta
AccountVerificationWarning: Tu cuenta no se ha verificado aún. No podrá agregar fiestas.
AccountVerificationCheckEmail: Por favor busque en su bandeja de entrada de correo electrónico un correo electrónico de verificación.
AccountVerificationCheckEmailDisclaimer: Si su correo electrónico de verificación aún no ha llegado, asegúrese de revisar su carpeta de correo no deseado. Hacemos todo lo posible para evitar que los correos electrónicos terminen en correo no deseado, pero a veces fallamos. Si aún no encuentra un correo electrónico de verificación, comuníquese con los administradores del sitio.
AccountVerificationResendButton: Reenviar correo electrónico de verificación
AccountDangerZoneTitle: Zona peligrosa
AccountDeleteButton: Eliminar cuenta
AccountDeleteWarning: ¿Está seguro de que desea eliminar su cuenta? Esto no se puede deshacer.

# Organiser Profile
OrganiserProfileTitle: Perfil de organizador
OrganiserDisplayNameLabel: Nombre para mostrar
OrganiserHomepageLabel: Página principal
OrganiserConsentReminderLabel: Quiero que me recuerden agregar fiestas.
OrganiserConsentReminderHelp: No enviaremos más de un correo electrónico de recordatorio por semana. Puedes desactivar esto en cualquier momento.
OrganiserSubmitButton: Guardar
OrganiserViewPublicProfileButton: Ver perfil público
OrganiserSaveSuccess: Perfil de organizador guardado con éxito

# Submit
SubmitTitle: Agrega tu fiesta
SubmitSingleParty: Fiesta única
SubmitRecurringParty: Fiesta recurrente
SubmitSinglePartyExplanation1: Una fiesta única ocurre solo una vez, en una fecha determinada.
SubmitSinglePartyExplanation2: También puedes editar, cancelar o eliminar la fiesta más tarde.
SubmitRecurringPartyExplanation1: Una fiesta recurrente ocurre varias veces, por ejemplo, todos los viernes.
SubmitRecurringPartyExplanation2: Cuando agregas una fiesta recurrente, el sitio genera fiestas en el futuro.
SubmitRecurringPartyExplanation3: Si edita un programa, todas las fiestas futuras generadas por él se editarán automáticamente.
SubmitRecurringPartyExplanation4: Si elimina un programa, todas las fiestas futuras en el programa se marcarán como canceladas y no se generarán futuras.

# Your parties
YourPartiesTitle: Tus fiestas
YourPartiesPartiesSubtitle: Fiestas
YourPartiesSchedulesSubtitle: Fiestas recurrentes
YourPartiesSubmitButton: Agregar fiesta
YourPartiesNoParties: Aún no has agregado ninguna fiesta.
YourPartiesEditPartyButton: Editar
YourPartiesEditScheduleButton: Editar
YourPartiesPublicPartyButton: Perfil público de la fiesta
YourPartiesDuplicatePartyButton: Duplicar
YourPartiesCancelPartyButton: Cancelar
YourPartiesUnCancelPartyButton: Anular la cancelación
YourPartiesDeletePartyWarning: ¿Estás seguro de que quieres eliminar esta fiesta? Esto no se puede deshacer.
YourPartiesDeletePartyButton: Eliminar

# Party form
PartyFormTitleLabel: Título
PartyFormDayLabel: Día
PartyFormAddressLabel: Dirección
PartyFormDescriptionLabel: Descripción
PartyFormStartLabel: Inicio
PartyFormHomepageLabel: Sitio web
PartyFormPriceLabel: Precio
PartyFormPriceHelp: Asegúrate de escribir GRATIS si la fiesta es gratis.
PartyFormPosterLabel: Póster
PartyFormPosterChooseInstruction: Elige una imagen de póster
PartyFormPosterNoPoster: Ningún póster seleccionado
PartyFormBackButton: Atras

# Submit Party
SubmitPartyTitle: Agregar fiesta
SubmitPartyButton: Agregar
SubmitPartySuccess: Fiesta añadida con éxito
SubmitPartyErrorUnverified: Su cuenta debe ser verificada antes de que pueda agregar fiestas.
SubmitPartyErrorNoOrganiser: Debe configurar un perfil de organizador en la descripción general de la cuenta antes de poder agregar una fiesta.

# View Party
AccountPartyErrorNotYourParty: Esta no es tu fiesta para ver.

# Edit Party
EditPartyTitle: Editar fiesta
EditPartyButton: Editar
EditPartySuccess: Fiesta editada con éxito
EditPartyPublicPartyProfile: Perfil público de la fiesta
EditPartyDayHelp: Ya no puedes editar el día de la fiesta. Si estabas buscando hacer eso, puedes cancelar esta fiesta y organizar otra, o duplicar esta fiesta para reorganizarla.
EditPartyErrorNotYourParty: Esta no es tu fiesta para editar.

# Duplicate Party
DuplicatePartyTitle: Duplicar fiesta
DuplicatePartyButton: Duplicar

# Cancel party
CancelPartyErrorNotYourParty: Esta no es tu fiesta para cancelar.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: Esta no es tu fiesta para anular la cancelación.

# Delete party
DeletePartyErrorNotYourParty: Esta no es tu fiesta para eliminar.

# Schedule Form
ScheduleFormTitleLabel: Título
ScheduleFormRecurrenceLabel: Recurrencia
ScheduleFormAddressLabel: Dirección
ScheduleFormDescriptionLabel: Descripción
ScheduleFormStartLabel: Inicio
ScheduleFormHomepageLabel: Sitio web
ScheduleFormPriceLabel: Precio
ScheduleFormPriceHelp: Asegúrate de escribir GRATIS si la fiesta es gratis.
ScheduleFormPosterLabel: Póster
ScheduleFormPosterChooseInstruction: Elige una imagen de póster
ScheduleFormPosterNoPoster: Ningún póster seleccionado
ScheduleFormBackButton: Atras

## Recurrence
RecurrenceWeeklyDescription weekday@String: Cada semana los #{weekday}
RecurrenceMonthlyDescriptionEvery: Cada
RecurrenceMonthlyDescriptionEveryFirst: Cada primero
RecurrenceMonthlyDescriptionEverySecond: Cada segundo
RecurrenceMonthlyDescriptionEveryThird: Cada tercer
RecurrenceMonthlyDescriptionEveryFourth: Cada cuarto
RecurrenceMonthlyDescriptionEveryLast: Cada último
RecurrenceMonthlyDescriptionEverySecondToLast: Cada segundo hasta el último
RecurrenceMonthlyDescriptionEveryThirdToLast: Cada tercer hasta el último
RecurrenceMonthlyDescriptionEveryFourthToLast: Cada cuarto hasta el último
RecurrenceMonthlyDescriptionDayOfWeekFirst weekday@String: Cada primero #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekSecond weekday@String: Cada segundo #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekThird weekday@String: Cada tercer #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekFourth weekday@String: Cada cuarto #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekLast weekday@String: Cada último #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekSecondToLast weekday@String: Cada segundo hasta el último #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekThirdToLast weekday@String: Cada tercer hasta el último #{weekday} del mes
RecurrenceMonthlyDescriptionDayOfWeekFourthToLast weekday@String: Cada cuarto hasta el último #{weekday} del mes

# Submit Schedule
SubmitScheduleTitle: Agregar programa
SubmitScheduleButton: Agregar
SubmitScheduleSuccess: Fiesta recurrente agregada con éxito
SubmitScheduleErrorUnverified: Su cuenta debe verificarse antes de que pueda agregar fiestas.
SubmitScheduleErrorNoOrganiser: Debe configurar un perfil de organizador en la descripción general de la cuenta antes de poder agregar una fiesta.

# View Schedule
AccountScheduleParties: Fiestas programadas

# Edit Schedule
EditScheduleTitle: Editar programa
EditScheduleButton: Guardar
EditScheduleSuccess: Fiesta recurrente editada con éxito
EditScheduleErrorNotYourSchedule: Esta no es tu fiesta para editar.

# Your schedules
YourSchedulesTitle: Tus programas de fiestas
YourSchedulesSubmitButton: Agregar un programa de fiestas
YourSchedulesNoSchedules: Aún no has agregado ningún programa de fiestas.
YourSchedulesEditScheduleButton: Editar
YourSchedulesDeleteScheduleWarning: ¿Seguro que quieres eliminar este programa de fiestas? Esto no se puede deshacer. Tenga en cuenta que las fiestas que ya se han programado no se eliminarán.
YourSchedulesDeleteScheduleButton: Eliminar
ScheduleTitle title@Text: #{title}

# Delete schedule
DeleteScheduleErrorNotYourSchedule: Este no es tu programa de fiestas para eliminar.

# Unsubscribe Reminder 
UnsubReminderTitle: Dado de baja de los correos electrónicos de recordatorio
UnsubReminderDescription: Se ha dado de baja con éxito de los correos electrónicos de recordatorio y ha revocado el consentimiento para recibir más correos electrónicos de recordatorio.

# Google Maps
GoogleMapAlt location@Text: Mapa de la zona alrededor de #{location}

# Pagination
PaginationPrevious: Anterior
PaginationNext: Siguiente

# Auto day
DayMoreThanAYearAgo: hace más de un año
Day11MonthsAgo: hace 11 meses
Day10MonthsAgo: hace 10 meses
Day9MonthsAgo: hace 9 meses
Day8MonthsAgo: hace 8 meses
Day7MonthsAgo: hace 7 meses
Day6MonthsAgo: hace 6 meses
Day5MonthsAgo: hace 5 meses
Day4MonthsAgo: hace 4 meses
Day3MonthsAgo: hace 3 meses
Day2MonthsAgo: hace 2 meses
Day1MonthAgo: hace un mes
Day4WeeksAgo: hace 4 semanas
Day3WeeksAgo: hace 3 semanas
Day2WeeksAgo: hace 2 semanas
Day1WeekAgo: hace una semana
Day6DaysAgo: hace 6 días
Day5DaysAgo: hace 5 días
Day4DaysAgo: hace 4 días
Day3DaysAgo: hace 3 días
Day2DaysAgo: hace 2 días
DayYesterday: ayer
DayToday: hoy
DayTomorrow: mañana
DayIn2Days: En 2 días
DayIn3Days: En 3 días
DayIn4Days: En 4 días
DayIn5Days: En 5 días
DayIn6Days: En 6 días
DayIn1Week: En una semana
DayIn2Week: En 2 semanas
DayIn3Week: En 3 semanas
DayIn4Week: En 4 semanas
DayIn1Month: En un mes
DayIn2Months: En 2 meses
DayIn3Months: En 3 meses
DayIn4Months: En 4 meses
DayIn5Months: En 5 meses
DayIn6Months: En 6 meses
DayIn7Months: En 7 meses
DayIn8Months: En 8 meses
DayIn9Months: En 9 meses
DayIn10Months: En 10 meses
DayIn11Months: En 11 meses
DayInMoreThanAYear: en más de un año

# Errors
NotFound: Página no encontrada
Gone: La página se ha perdido
