# Translators
# marierosepoesen@telenet.be

# Logo
Logo title@Text: #{title} Logo

# Home Page
HomeDescription title@Text: TODO #{title}: Where can I dance? Find social dance parties today, whether you are looking for Salsa, Bachata, Kizomba, Mambo, Cha-Cha-Cha, Tango, Zouk, Swing, Lindy Hop, or another dance, you can find it here.
HomeSubtitleQuestion: Où puis-je danser?
HomeFormLocation: Mon lieu
HomeFormLocationUnable: Impossible de trouver votre lieu
HomeFormLocationNotSupported: Votre géolocation n’est pas soutenue par votre navigateur
HomeFormLocationInProgress: Localisation…
HomeFormLocationDone: Localisé
HomeFormSearch: Recherche
HomeFormHelp: Appuyez sur le bouton chercher pour trouver des soirées dans les environs de votre endroit actuel.

# Explore
ExploreTitle: Explorez le monde de la danse sociale!
ExploreDescription: La danse sociale existe partout dans le monde, trouvez où aller!
ExploreButton: Trouvez
ExploreUpcomingParties number@String: #{number} prochaines soirées
ExploreSkylineAlt location@Text: Night-time skyline de #{location}

## Footer
FooterGeocodingAttribution: [Geocoding by OpenStreetMaps Nominatim]
FooterOpenstreetmapCopyright: © OpenStreetMap contributeurs

# Navbar
NavFind: Trouvez une soirée
NavSubmitParty: TODO
NavAccount: Compte
NavOrganiser: Profil d’organisateur
NavParties: Mes soirées
NavLanguage: Langue
NavAdmin: Panneau administrateur
NavSignUp: S’enregistrer
NavLogIn: Login
NavLogOut: Logout

# Form messages
InvalidLatitude lat@String: TODO Invalid latitude: #{lat}
InvalidLongitude lon@String: TODO Invalid longitude: #{lon}

# Search Results
SearchTitleAroundYourLocationToday: Soirées de danse près de votre endroit aujourd’hui
SearchTitleAroundYourLocationOnDay day@String: Soirées de danse près de votre lieu le #{day}
SearchTitleAroundAddressToday address@Text: Soirées de danse près de #{address} aujourd’hui
SearchTitleAroundAddressOnDay address@Text day@String: Soirées de danse près de #{address} le #{day}
SearchDescriptionAroundYourLocationToday: Une liste de soirées de danse près de chez vous
SearchDescriptionAroundYourLocationOnDay day@String: Une liste de soirées de danse près de votre lieu le #{day}
SearchDescriptionAroundAddressToday address@Text: Une liste de soirées de danse près de #{address}
SearchDescriptionAroundAddressOnDay address@Text day@String: Une liste de soirées de danse près #{address} le #{day}
SearchPartiesAroundAddress address@Text: Soirées de danse près de #{address}
SearchPartiesAroundYourLocation: Soirée de danse près de votre lieu
SearchNoParties: Pas de soirées de danse pour cette date.
SearchPosterAlt title@Text day@String: Affiche pour #{title} le #{day}
SearchNoResults: Nous n’avons pas d’information concernant cette region en ce moment.
SearchNoResultsHelp: Nous avons besoin de votre aide pour rassembler des informations pour cette région. Contactez les organisateurs de cette soirée et informez-lez de cette page. Si vous organisez des soirées dans cette région, inscrivez-vous et publiez vos soirées ici.  

SearchNavEarlier: Ultérieurement
SearchNavLater: Plus tard

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: ANNULEE: #{title}
PartyDescription description@Text: #{description}
PartyWithoutDescription: Soirée sans description

PartyAddress address@Text: Adresse: #{address}
PartyOrganiser name@Text: Organisateur: #{name}
PartyOrganiserTitle organiserName@Text: TODO #{organiserName}
PartyPrice price@Text: Prix: #{price}
PartyHomepage: Site internet
PartyHomepageTitle partyTitle@Text: TODO Homepage of #{partyTitle}
PartyDownloadCalendarEvent: Téléchargez calendrier des évènements
PartyDownloadCalendarEventTitle partyTitle@Text: TODO Download Calendar Event for #{partyTitle}
PartyAddToGoogleCalendar: Ajoutez au Calendrier Google
PartyAddToGoogleCalendarTitle partyTitle@Text: TODO Add #{partyTitle} to Google Calendar

PartyDescriptionDay day@String: TODO on #{day}
PartyDescriptionDateTime day@String start@String: TODO on #{day} at #{start}
PartyDescriptionOrganiser name@Text: TODO by #{name}
PartyDescriptionAddress address@Text: TODO address: TODO #{address}

ExternalEventCaution: Information trouvée en cherchant sur le web, traitez cette information avec prudence. 

# Organiser Page
OrganiserTitle name@Text: Profil de l’organisateure: #{name}
OrganiserHomepage: TODO Homepage
OrganiserHomepageTitle name@Text: TODO Homepage of #{name}
OrganiserDescription name@Text: Le profil de l’organisateur #{name} et une liste de leur prochaines soirées
OrganiserName name@Text: Organisateur: #{name}
OrganiserUpcomingParties: Prochaines soirées
OrganiserNoUpcomingParties: Pas de prochaines soirées

# Poster
PosterAltFull title@Text day@String organiser@Text: Affiche pour #{title} le #{day} par #{organiser}
PosterAltTitle title@Text day@String: Affiche pour #{title} le #{day}
PosterAltSchedule title@Text recurrenceDescription@Text organiser@Text: TODO Poster for #{title}, #{recurrenceDescription} by #{organiser}

# Registration
RegistrationTitle: Salsa Parties Today: S'enregistrer
RegistrationDescription: Créer un compte à Salsa Parties Today.
RegistrationEmailAddressLabel: Adresse Email
RegistrationPassphraseLabel: Mot de passe
RegistrationConfirmPassphraseLabel: Confirmer mot de passe
RegistrationSignUpButton: Inscrivez-vous
RegistrationLogInButton: Se connecter
RegistrationErrorAccountAlreadyExists: Un compte avec cet identifiant existe déjà

# Login
LoginTitle: Login
LoginDescription: Login avec votre compte
LoginEmailAddressLabel: Adresse Email
LoginPassphraseLabel: Mot de passe
LoginLogInButton: Login
LoginSignUpButton: Inscrivez-vous

# Verification Email
VerificationEmailSubject title@Text: #{title} vérification adresse email
VerificationEmailTitle title@Text: #{title} inscription
VerificationEmailTextCTA: Vérifiez votre adresse email en suivant ce lien:
VerificationEmailHtmlCTA: Vérifiez votre adresse email en cliquant sur le lien ci-dessous
VerificationEmailButton: Vérifiez email
VerificationEmailInvitation: On espère vous voir bientôt.
VerificationEmailExplanation title@Text: Vous recevez cet email parce que vous avez essayé de vous inscrire à #{title}.

VerificationEmailFailure: L’envoi du mail de vérification a été refusé.
VerificationErrorAlreadyVerified: Ce compte a déjà été vérifié.

# Account Page
AccountOverviewTitle: Account Compte
AccountEmailAddress emailAddress@Text: Adresse Email: #{emailAddress} 
AccountVerificationTitle: Vérification Compte
AccountVerificationWarning: Votre compte n’a pas encore été vérifié. Vous ne pouvez pas encore soumettre des soirées.
AccountVerificationCheckEmail: Vérifiez svp si vous avez reçu dans votre boîte de réception l’email de vérification.
AccountVerificationCheckEmailDisclaimer: Si votre email de verification n’est pas encore arrivé, vérifiéz svp votre fichier spam. Nous faisons de notre mieux pour éviter que les emails arrivent dans le dossier spam mais pafois nous échouons. Si vous n’avez toujours pas reçu le mail de vérification, contactez svp les administrateurs du site.
AccountVerificationResendButton: Renvoyez email de vérification
AccountDangerZoneTitle: Zone Danger
AccountDeleteButton: Supprimez compte
AccountDeleteWarning: Etes-vous sûr vouloir annuler votre compte? Il ne sera pas possible de le défaire.

# Organiser Profile
OrganiserProfileTitle: Profil de l’organisateur
OrganiserDisplayNameLabel: Affichage Nom
OrganiserHomepageLabel: TODO Homepage
OrganiserConsentReminderLabel: TODO I want to be reminded to submit parties.
OrganiserConsentReminderHelp: TODO We will send no more than one reminder email per week. You can turn this off at any time.
OrganiserSubmitButton: Soumettre
OrganiserViewPublicProfileButton: Voir le Profil Public
OrganiserSaveSuccess: TODO Succesfully saved organiser profile

# Submit
SubmitTitle: TODO Add your party
SubmitSingleParty: TODO Single party
SubmitRecurringParty: TODO Recurring party
SubmitSinglePartyExplanation1: TODO A single party happens only once, on a given date.
SubmitSinglePartyExplanation2: TODO You can still edit, cancel or delete the party later.
SubmitRecurringPartyExplanation1: TODO A recurring party happens multiple times, for example every friday.
SubmitRecurringPartyExplanation2: TODO When you schedule a recurring party, the site generates parties into the future.
SubmitRecurringPartyExplanation3: TODO If you edit a schedule, all future parties generated by it will be edited automatically.
SubmitRecurringPartyExplanation4: TODO If you delete a schedule, all future parties in the schedule will be marked as cancelled, and no future ones will be generated.

# Your parties
YourPartiesTitle: Vos Soirées
YourPartiesPartiesSubtitle: TODO Parties
YourPartiesSchedulesSubtitle: TODO Recurring parties
YourPartiesSubmitButton: Soumettez Soirée
YourPartiesNoParties: Vous n’avez pas encore envoyé/soumis des soirées.
YourPartiesEditPartyButton: TODO Edit
YourPartiesEditScheduleButton: TODO Edit
YourPartiesPublicPartyButton: Profil soirée publique
YourPartiesDuplicatePartyButton: Dupliquez
YourPartiesCancelPartyButton: Annuler
YourPartiesUnCancelPartyButton: Non-annulation
YourPartiesDeletePartyWarning: Etes-vous sûr vouloir annuler cette soirée. Ceci ne peut pas être défait.
YourPartiesDeletePartyButton: Annuler

# Party form
PartyFormTitleLabel: Titre
PartyFormDayLabel: Jour
PartyFormAddressLabel: Adresse
PartyFormDescriptionLabel: Description
PartyFormStartLabel: Début
PartyFormHomepageLabel: Site web
PartyFormPriceLabel: Prix
PartyFormPriceHelp: N’oubliez pas d’écrire GRATUIT si la participation à votre soirée est gratuite.
PartyFormPosterLabel: Affiche
PartyFormPosterChooseInstruction: Choissisez une image pour l’affiche
PartyFormPosterNoPoster: Pas d’affiche sélectionnée
PartyFormBackButton: Retour

# Submit Party 
SubmitPartyTitle: Inscrivez Soirée
SubmitPartyButton: Inscrivez
SubmitPartySuccess: Vous avez inscrit avec succès la soirée
SubmitPartyErrorUnverified: Votre compte sera vérifié avant que vous pouvez inscrire des soirées.
SubmitPartyErrorNoOrganiser: TODO You must set up an organiser profile in the account overview before you can submit a party.

# View Party
AccountPartyErrorNotYourParty: TODO This is not your party to view.

# Edit Party
EditPartyTitle: Soumettre Soirée
EditPartyButton: Soumettre
EditPartySuccess: Publication de la soirée réussie
EditPartyPublicPartyProfile: Profil soirée publique
EditPartyDayHelp: Vous ne pouvez plus modifier le jour de la soirée. Si vous vouliez modifier, vous pouvez annuler cette soirée et/ou organiser une autre soirée, ou copier cette soirée et la réorganiser.
EditPartyErrorNotYourParty: Ceci n’est pas votre soirée à éditer.

# Duplicate Party
DuplicatePartyTitle: Soumettre soirée
DuplicatePartyButton: Soumettre

# Cancel party
CancelPartyErrorNotYourParty: Ceci n’est pas votre soirée à annuler.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: Ceci n’est pas votre soirée à ne pas annuler.

# Delete party
DeletePartyErrorNotYourParty: Ceci n’est pas votre soirée à annuler.

# Schedule Form
ScheduleFormTitleLabel: TODO Title
ScheduleFormRecurrenceLabel: TODO Recurrence
ScheduleFormAddressLabel: TODO Address
ScheduleFormDescriptionLabel: TODO Description
ScheduleFormStartLabel: TODO Start
ScheduleFormHomepageLabel: TODO Website
ScheduleFormPriceLabel: TODO Price
ScheduleFormPriceHelp: TODO Make sure to write FREE if the party is free.
ScheduleFormPosterLabel: TODO Poster
ScheduleFormPosterChooseInstruction: TODO Choose a poster image
ScheduleFormPosterNoPoster: TODO No poster selected
ScheduleFormBackButton: TODO Back

## Recurrence
RecurrenceWeeklyType: TODO Weekly
RecurrenceWeeklyDescription weekday@String: TODO Every week on #{weekday}

# Submit Schedule
SubmitScheduleTitle: TODO Submit Schedule
SubmitScheduleButton: TODO Submit
SubmitScheduleSuccess: TODO Succesfully submitted recurring party
SubmitScheduleErrorUnverified: TODO Your account needs to verified before you can submit parties.
SubmitScheduleErrorNoOrganiser: TODO You must set up an organiser profile in the account overview before you can submit a party.

# View Schedule
AccountScheduleParties: TODO Scheduled parties

# Edit Schedule
EditScheduleTitle: TODO Edit Schedule
EditScheduleButton: TODO Save
EditScheduleSuccess: TODO Succesfully edited recurring party
EditScheduleErrorNotYourSchedule: TODO This is not your party to edit.

# Your schedules
YourSchedulesTitle: TODO Your party schedules
YourSchedulesSubmitButton: TODO Submit a party schedule
YourSchedulesNoSchedules: TODO You have not submitted any party schedules yet.
YourSchedulesEditScheduleButton: TODO Edit
YourSchedulesDeleteScheduleWarning: TODO Are you sure you want to delete this party schedule? This cannot be undone. Note that parties that have already been scheduled will not be deleted.
YourSchedulesDeleteScheduleButton: TODO Delete
ScheduleTitle title@Text: TODO #{title}

# Delete schedule
DeleteScheduleErrorNotYourSchedule: TODO This is not your party schedule to delete.


# Unsubscribe Reminder
UnsubReminderTitle: TODO Unsubscribed from reminder emails
UnsubReminderDescription: TODO You have succesfully unsubscribed from reminder emails and revoked consent to receive any further reminder emails.

# Google Maps
GoogleMapAlt location@Text: TODO Map of the area around #{location}

# Pagination
PaginationPrevious: Page Précédente
PaginationNext: Page Suivante

# Auto day
DayMoreThanAYearAgo: Il y a plus qu’un an
Day11MonthsAgo: Il y a 11 mois
Day10MonthsAgo: Il y a 10 mois
Day9MonthsAgo: Il y a 9 mois
Day8MonthsAgo: Il y a 8 mois
Day7MonthsAgo: Il y a 7 mois
Day6MonthsAgo: Il y a 6 mois
Day5MonthsAgo: Il y a 5 mois
Day4MonthsAgo: Il y a 4 mois
Day3MonthsAgo: Il y a 3 mois
Day2MonthsAgo: Il y a 2 mois
Day1MonthAgo: Il y a un mois
Day4WeeksAgo: Il y a 4 semaines
Day3WeeksAgo: Il y a 3 semaines
Day2WeeksAgo: Il y a 2 semaines
Day1WeekAgo: Il y a une semaine
Day6DaysAgo: Il y a 6 jours
Day5DaysAgo: Il y a 5 jours
Day4DaysAgo: Il y a 4 jours
Day3DaysAgo: Il y a 3 jours
Day2DaysAgo: Il y a 2 jours
DayYesterday: Hier
DayToday: Aujourd’hui
DayTomorrow: Demain
DayIn2Days: Dans 2 jours
DayIn3Days: Dans 3 jours
DayIn4Days: Dans 4 jours
DayIn5Days: Dans 5 jours
DayIn6Days: Dans 6 jours
DayIn1Week: Dans une semaine
DayIn2Week: Dans 2 semaines
DayIn3Week: Dans 3 semaines
DayIn4Week: Dans 4 semaines
DayIn1Month: Dans un mois
DayIn2Months: Dans 2 mois
DayIn3Months: Dans 3 mois
DayIn4Months: Dans 4 mois
DayIn5Months: Dans 5 mois
DayIn6Months: Dans 6 mois
DayIn7Months: Dans 7 mois
DayIn8Months: Dans 8 mois
DayIn9Months: Dans 9 mois
DayIn10Months: Dans 10 mois
DayIn11Months: Dans 11 mois
DayInMoreThanAYear: Plus qu’un an à partir de maintenant

# Errors
NotFound: Page non trouvée
