# Translators
# marierosepoesen@telenet.be

# Logo
Logo title@Text: #{title} Logo

# Home Page
HomeDescription title@Text: #{title}: Où puis-j’aller danser? Trouvez des soirées de danse aujourd'hui. Si vous cherchez à danser la Salsa, Bachata, Kizomba, Mambo, Cha-Cha-Cha, Tango, Zouk, Swing, Lindy Hop ou une autre danse, vous la trouverez ici.
HomeSubtitleQuestion: Où puis-j'aller danser?
HomeFormSearch: Recherche
HomeAdvancedLabel: Appprofondie

# Advanced search
AdvancedSearchTitle: Recherche appprofondie
AdvancedSearchDescription: Trouvez les soirées de danse que vous cherchez.
AdvancedSearchFormLocationLabel: Lieu
AdvancedSearchFormDistanceLabel: Distance
AdvancedSearchFormBeginLabel: Du
AdvancedSearchFormEndLabel: Au
AdvancedSearchFormDanceStyleLabel: Style de dance
AdvancedSearchFormSubmit: Cherchez

# Locate me button
LocateMePlaceholder: Entrez emplacement
LocateMeLocation: Mon lieu
LocateMeUnable: Impossible de trouver votre lieu
LocateMeInProgress: Recherche en cours...
LocateMeDone: Lieu trouvé
LocateMeHelpBefore: Appuyez sur la touche "mon lieu" pour utiliser votre lieu actuel.
LocateMeHelpAfter: Votre lieu actuel sera utilisé pour la recherche à moins que vous introduisez un autre lieu ci-dessus.

# Explore
ExploreTitle: Explorez le monde de la danse sociale!
ExploreDescription: La danse sociale existe partout dans le monde, trouvez où aller!
ExploreButton: Trouvez
ExploreUpcomingParties number@String: #{number} prochaines soirées
ExploreSkylineAlt location@Text: Night-time skyline de #{location}

## Footer
GiveFeedback: Donnez votre avis
FooterGeocodingAttribution: Geocoding by OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap contributeurs

# Navbar
NavFind: Trouvez une soirée
NavSubmitParty: Ajoutez votre soirée de danse
NavAccount: Compte
NavOrganiser: Profil d’organisateur
NavParties: Mes soirées
NavLanguage: Langue
NavAdmin: Panneau administrateur
NavSignUp: S’enregistrer
NavLogIn: Login
NavLogOut: Logout

# Form messages
InvalidLatitude lat@String: Latitude invalide: #{lat}
InvalidLongitude lon@String: Longitude invalide: #{lon}
DistanceTooGreat distance@String: Distance trop élevée: #{distance} km
EndBeforeBegin: La date ultérieure est avant la date de début.
EndTooFarAhead: Search date range too big. Recherche période trop longue.
AddressOrCoordinates: Vous devez introduire une période ou des coordonnées.

# Search Results

## Title

### Without dance style
SearchTitleAroundYourLocationToday: Soirées de danse près de votre lieu aujourd’hui
SearchTitleAroundYourLocationOnDay day@String: Soirées de danse près de votre lieu le #{day}
SearchTitleAroundYourLocationFromTo begin@String end@String: Soirées de danse près de votre lieu à partir de #{begin} jusqu'à #{end}
SearchTitleAroundAddressToday address@Text: Soirées de danse près de #{address} aujourd’hui
SearchTitleAroundAddressOnDay address@Text day@String: Soirées de danse près de #{address} le #{day}
SearchTitleAroundAddressFromTo address@Text begin@String end@String: Soirées de danse près de #{address} entre #{begin} et #{end}

### With dance style
SearchTitleDanceStyleAroundYourLocationToday danceStyle@Text: Soirées #{danceStyle} près de votre lieu aujourd’hui
SearchTitleDanceStyleAroundYourLocationOnDay danceStyle@Text day@String: Soirées #{danceStyle} près de votre lieu le #{day}
SearchTitleDanceStyleAroundYourLocationFromTo danceStyle@Text begin@String end@String: Soirées #{danceStyle} près de votre lieu à partir de #{begin} jusqu'à #{end}
SearchTitleDanceStyleAroundAddressToday danceStyle@Text address@Text: Soirées #{danceStyle} près de #{address} aujourd’hui
SearchTitleDanceStyleAroundAddressOnDay danceStyle@Text address@Text day@String: Soirées #{danceStyle} près de #{address} le #{day}
SearchTitleDanceStyleAroundAddressFromTo danceStyle@Text address@Text begin@String end@String: Soirées #{danceStyle} près de #{address} entre #{begin} et #{end}

## Description

### Without dance style
SearchDescriptionAroundYourLocationToday: Une liste de soirées de danse près de vous
SearchDescriptionAroundYourLocationOnDay day@String: Une liste de soirées de danse près de votre lieu le #{day}
SearchDescriptionAroundYourLocationFromTo begin@String end@String: Une liste de soirées de danse près de votre lieu entre #{begin} et #{end}
SearchDescriptionAroundAddressToday address@Text: Une liste de soirées de danse près de #{address}
SearchDescriptionAroundAddressOnDay address@Text day@String: Une liste de soirées de danse près #{address} le #{day}
SearchDescriptionAroundAddressFromTo address@Text begin@String end@String: Une liste de soirées de danse près de #{address} entre #{begin} et #{end}

### With dance style
SearchDescriptionDanceStyleAroundYourLocationToday danceStyle@Text:  Une liste de soirées #{danceStyle} près de vous
SearchDescriptionDanceStyleAroundYourLocationOnDay danceStyle@Text day@String:  Une liste de soirées #{danceStyle} près de votre lieu le #{day}
SearchDescriptionDanceStyleAroundYourLocationFromTo danceStyle@Text begin@String end@String:  Une liste de soirées #{danceStyle} près de votre lieu entre #{begin} et #{end}
SearchDescriptionDanceStyleAroundAddressToday danceStyle@Text address@Text:  Une liste de soirées #{danceStyle} près de #{address}
SearchDescriptionDanceStyleAroundAddressOnDay danceStyle@Text address@Text day@String:  Une liste de soirées #{danceStyle} près #{address} le #{day}
SearchDescriptionDanceStyleAroundAddressFromTo danceStyle@Text address@Text begin@String end@String:  Une liste de soirées #{danceStyle} près de #{address} entre #{begin} et #{end}

## Search Errors
SearchNoParties: Pas de soirées de danse pour cette date.
SearchPosterAlt title@Text day@String: Affiche pour #{title} le #{day}
SearchNoResults: Nous n’avons pas d’information concernant cette region en ce moment.
SearchNoResultsHelp: Nous avons besoin de votre aide pour rassembler des informations pour cette région. Contactez les organisateurs de cette soirée et informez-lez de cette page. Si vous organisez des soirées dans cette région, inscrivez-vous et publiez vos soirées ici.

SearchNavEarlier: Ultérieurement
SearchNavLater: Plus tard

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: SUPPRIMÉE: #{title}
PartyDescription description@Text: #{description}

PartyAddress address@Text: Adresse: #{address}
PartyOrganiser name@Text: Organisateur: #{name}
PartyOrganiserTitle organiserName@Text: Nom organisateur: #{organiserName}
PartyPrice price@Text: Prix: #{price}
PartyHomepage: Site internet
PartyHomepageTitle partyTitle@Text: Page d’accueil de #{partyTitle}
PartyDownloadCalendarEvent: Téléchargez calendrier des évènements
PartyDownloadCalendarEventTitle partyTitle@Text: Télécharger le calendrier d’évènements de #{partyTitle}
PartyAddToGoogleCalendar: Ajoutez au Calendrier Google
PartyAddToGoogleCalendarTitle partyTitle@Text: Ajoutez #{partyTitle} au calendrier Google

PartyDescriptionDay day@String: le #{day}
PartyDescriptionDateTime day@String start@String: le #{day} à #{start}
PartyDescriptionOrganiser name@Text: par #{name}
PartyDescriptionAddress address@Text: adresse: #{address}

ExternalEventCaution: Information trouvée en cherchant sur le web, traitez cette information avec prudence.

# Organiser Page
OrganiserTitle name@Text: Profil de l’organisateur: #{name}
OrganiserHomepage: Page d’accueil
OrganiserHomepageTitle name@Text: Page d’accueil de #(nom)
OrganiserDescription name@Text: Le profil de l’organisateur #{name} et une liste de leures prochaines soirées
OrganiserName name@Text: Organisateur: #{name}
OrganiserUpcomingParties: Prochaines soirées
OrganiserNoUpcomingParties: Pas de prochaines soirées
OrganiserCalendarTitle: URL du calendrier
OrganiserCalendarExplanation: Ajoutez tous ces évènements à votre agenda en souscrivant à l'abonnement par ce lien:

# Poster
PosterAltFull title@Text day@String organiser@Text: Affiche pour #{title} le #{day} par #{organiser}
PosterAltTitle title@Text day@String: Affiche pour #{title} le #{day}
PosterAltSchedule title@Text recurrenceDescription@Text organiser@Text: Affiche pour #(titre) par #(organisateur)

# Registration
RegistrationTitle: S'enregistrer
RegistrationDescription: Créer un compte.
RegistrationEmailAddressLabel: Adresse Email
RegistrationPassphraseLabel: Mot de passe
RegistrationConfirmPassphraseLabel: Confirmer mot de passe
RegistrationSignUpButton: Inscrivez-vous
RegistrationLogInButton: Se connecter
RegistrationErrorAccountAlreadyExists: Un compte avec cet identifiant existe déjà.

# Login
LoginTitle: Login
LoginDescription: Login avec votre compte
LoginEmailAddressLabel: Adresse email
LoginPassphraseLabel: Mot de passe
LoginLogInButton: Login
LoginSignUpButton: Inscrivez-vous

# Verification Email
VerificationEmailSubject title@Text: #{title} vérification adresse email
VerificationEmailTitle title@Text: #{title} inscription
VerificationEmailTextCTA: Vérifiez votre adresse email en suivant ce lien:
VerificationEmailHtmlCTA: Vérifiez votre adresse email en cliquant sur le lien ci-dessous
VerificationEmailButton: Vérifiez email
VerificationEmailInvitation: On espère vous voir bientôt.
VerificationEmailExplanation title@Text: Vous recevez cet email parce que vous avez essayé de vous inscrire à #{title}.
VerificationEmailFailure: L’envoi du mail de vérification a été refusé.
VerificationErrorAlreadyVerified: Ce compte a déjà été vérifié.

# Account Page
AccountOverviewTitle: Compte
AccountEmailAddress emailAddress@Text: Adresse Email: #{emailAddress}
AccountVerificationTitle: Vérification compte
AccountVerificationWarning: Votre compte n’a pas encore été vérifié. Vous ne pouvez pas encore soumettre des soirées.
AccountVerificationCheckEmail: Vérifiez svp si vous avez reçu dans votre boîte de réception l’email de vérification.
AccountVerificationCheckEmailDisclaimer: Si votre email de verification n’est pas encore arrivé, vérifiéz svp votre fichier spam. Nous faisons de notre mieux pour éviter que les emails arrivent dans le dossier spam mais pafois nous échouons. Si vous n’avez toujours pas reçu le mail de vérification, contactez svp les administrateurs du site.
AccountVerificationResendButton: Renvoyez email de vérification
AccountDangerZoneTitle: Zone Danger
AccountDeleteButton: Supprimez compte
AccountDeleteWarning: Etes-vous sûr vouloir supprimer votre compte? Il ne sera pas possible de le défaire.

# Organiser Profile
OrganiserProfileTitle: Profil de l’organisateur
OrganiserDisplayNameLabel: Affichage Nom
OrganiserHomepageLabel: Page d’accueil
OrganiserConsentReminderLabel: Je veux recevoir des rappels pour introduire des soirées sociales.
OrganiserConsentReminderHelp: Nous ne vous enverrons pas plus qu’un email de rappel par semaine. Vous pouvez supprimer les rappels à tout moment.
OrganiserSubmitButton: Soumettre
OrganiserViewPublicProfileButton: Voir le profil public
OrganiserSaveSuccess: Le profil de l’organisateur a été sauvegardé avec succès.

# Submit
SubmitTitle: Ajoutez votre soirée de danse
SubmitSingleParty: Fête non récurrente
SubmitRecurringParty: Fête périodique
SubmitSinglePartyExplanation1: Une fête non récurrente n’aura lieu qu’une fois à une date précise.
SubmitSinglePartyExplanation2: Vous pouvez toujours éditer ou supprimer la fête plus tard.
SubmitRecurringPartyExplanation1: Une fête récurrente aura lieu plusieurs fois, par exemple chaque vendredi.
SubmitRecurringPartyExplanation2: Si vous planifiez une fête récurrente, le site génère des fêtes à l’avenir.
SubmitRecurringPartyExplanation3: Si vous éditez un schéma, toutes les fêtes générées seront éditez automatiquement.
SubmitRecurringPartyExplanation4: Si vous supprimez un schéma, toutes les fêtes à l’avenir dans ce schéma seront marquées comme annulées. Les fêtes à l’avenir ne seront plus générées.

# Your parties
YourPartiesTitle: Vos Soirées
YourPartiesPartiesSubtitle: Fêtes
YourPartiesSchedulesSubtitle: Fêtes récurrentes
YourPartiesSubmitButton: Soumettez Soirée
YourPartiesNoParties: Vous n’avez pas encore soumis des soirées.
YourPartiesEditPartyButton: Editez
YourPartiesEditScheduleButton: Editez
YourPartiesPublicPartyButton: Profil soirée publique
YourPartiesDuplicatePartyButton: Dupliquez
YourPartiesCancelPartyButton: Supprimer
YourPartiesUnCancelPartyButton: Non-annulation
YourPartiesDeletePartyWarning: Etes-vous sûr vouloir supprimer cette soirée. Ceci ne peut pas être défait.
YourPartiesDeletePartyButton: Supprimer

# Party form
PartyFormTitleLabel: Titre
PartyFormDayLabel: Jour
PartyFormAddressLabel: Adresse
PartyFormDescriptionLabel: Description
PartyFormStartLabel: Début
PartyFormHomepageLabel: Site internet
PartyFormPriceLabel: Prix
PartyFormPriceHelp: N’oubliez pas d’écrire GRATUIT si la participation à votre soirée est gratuite.
PartyFormPosterLabel: Affiche
PartyFormPosterChooseInstruction: Choissisez une image pour l’affiche
PartyFormPosterNoPoster: Pas d’affiche sélectionnée
PartyFormBackButton: Retour

# Submit Party 
SubmitPartyTitle: Inscrivez soirée
SubmitPartyButton: Inscrivez
SubmitPartySuccess: Vous avez inscrit avec succès la soirée
SubmitPartyErrorUnverified: Votre compte devra être vérifié avant que vous pouvez inscrire des soirées.
SubmitPartyErrorNoOrganiser: Vous devez crééer un profile d’organisateur dans l’aperçu du compte avant de pouvoir soumettre une soirée de danse.

# View Party
AccountPartyErrorNotYourParty: Ceci n’est pas votre soirée à revoir.

# Edit Party
EditPartyTitle: Soumettre soirée
EditPartyButton: Soumettre
EditPartySuccess: Publication de la soirée réussie
EditPartyPublicPartyProfile: Profil soirée publique
EditPartyDayHelp: Vous ne pouvez plus modifier le jour de la soirée. Si vous vouliez modifier, vous pouvez supprimer cette soirée et/ou organiser une autre soirée, ou copier cette soirée et la réorganiser.
EditPartyErrorNotYourParty: Ceci n’est pas votre soirée à éditer.

# Duplicate Party
DuplicatePartyTitle: Soumettre soirée
DuplicatePartyButton: Soumettre

# Cancel party
CancelPartyErrorNotYourParty: Ceci n’est pas votre soirée à supprimer.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: Ceci n’est pas votre soirée à ne pas supprimer.

# Delete party
DeletePartyErrorNotYourParty: Ceci n’est pas votre soirée à supprimer.

# Schedule Form
ScheduleFormTitleLabel: Titre
ScheduleFormRecurrenceLabel: Récurrence
ScheduleFormAddressLabel: Adresse
ScheduleFormDescriptionLabel: Description
ScheduleFormStartLabel: Début
ScheduleFormHomepageLabel: Site web
ScheduleFormPriceLabel: Prix
ScheduleFormPriceHelp: N’oubliez pas d’indiquer GRATUIT si la soirée est sans prix d’entrée.
ScheduleFormPosterLabel: Affiche
ScheduleFormPosterChooseInstruction: Choisissez une image pour l’affiche
ScheduleFormPosterNoPoster: Pas d’affiche sélectionnée
ScheduleFormBackButton: Retour

## Recurrence
RecurrenceWeeklyDescription weekday@String: Chaque semaine le #{weekday}
RecurrenceMonthlyDescriptionEvery: Chaque
RecurrenceMonthlyDescriptionEveryFirst: Chaque premièr
RecurrenceMonthlyDescriptionEverySecond: Chaque deuxième
RecurrenceMonthlyDescriptionEveryThird: Chaque troisième
RecurrenceMonthlyDescriptionEveryFourth: Chaque quatrième
RecurrenceMonthlyDescriptionEveryLast: Chaque dernier
RecurrenceMonthlyDescriptionEverySecondToLast: Chaque avant-dernier
RecurrenceMonthlyDescriptionEveryThirdToLast: Chaque troisième au dernier
RecurrenceMonthlyDescriptionEveryFourthToLast: Chaque quatrième au dernier
RecurrenceMonthlyDescriptionDayOfWeekFirst weekday@String: Chaque première #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekSecond weekday@String: Chaque deuxième #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekThird weekday@String: Chaque troisième #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekFourth weekday@String: Chaque quatrième #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekLast weekday@String: Chaque dernier #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekSecondToLast weekday@String: Chaque avant-dernier #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekThirdToLast weekday@String: Chaque troisième au dernier #{weekday} du mois
RecurrenceMonthlyDescriptionDayOfWeekFourthToLast weekday@String: Chaque quatrième au dernier #{weekday} du mois

# Submit Schedule
SubmitScheduleTitle: Choissisez l’horaire/le calendrier
SubmitScheduleButton: Soumettez
SubmitScheduleSuccess: Vous avez introduit avec succès les fêtes récurrentes
SubmitScheduleErrorUnverified: Votre compte doit être vérifié avant que vous ne puissiez introdure des fêtes.
SubmitScheduleErrorNoOrganiser: Vous devez créer un profile d’organisateur dans l’aperçu du compte avant de pouvoir soumettre une fête.

# View Schedule
AccountScheduleParties: Fêtes planifiées

# Edit Schedule
EditScheduleTitle: Editez un calendrier
EditScheduleButton: Sauvegardez
EditScheduleSuccess: Vous avez éditez avec succès les fêtes récurrentes.
EditScheduleErrorNotYourSchedule: Ceci n’est pas votre fête à éditer.

# Your schedules
YourSchedulesTitle: Le calendrier de vos fêtes
YourSchedulesSubmitButton: Soumettez un programme de fête
YourSchedulesNoSchedules: Vous n’avez pas encore soumis un programme de fête.
YourSchedulesEditScheduleButton: Editez
YourSchedulesDeleteScheduleWarning: Etez-vous sûr vouloir supprimer cette fête programmée? Ceci ne peut être défait. Notez que les fêtes déjà programmées ne seront pas supprimées.
YourSchedulesDeleteScheduleButton: Supprimez
ScheduleTitle title@Text: #{title}

# Delete schedule
DeleteScheduleErrorNotYourSchedule: Ceci n’est pas votre fête à supprimer.

# Unsubscribe Reminder
UnsubReminderTitle: Désinscription de rappels d'emails.
UnsubReminderDescription: Vous vous êtes désinscrit à recevoir des emails de rappel avec succès et vous avez indiqué ne plus vouloir recevoir des emails à l’avenir.

# Google Maps
GoogleMapAlt location@Text: Carte des environs #{location}

# Pagination
PaginationPrevious: Page Précédente
PaginationNext: Page Suivante

# Dance Styles
DanceStyleFilter: Filtre
AllDanceStyles: Tous les styles de danse
Salsa: Salsa
Bachata: Bachata
ChaChaCha: Cha-Cha-Cha
Kizomba: Kizomba
Zouk: Zouk
LindyHop: Lindy Hop
Tango: Tango
WestCoastSwing: West Coast Swing

# Auto day
DayMoreThanAYearAgo: Il y a plus qu’un an
Day11MonthsAgo: Il y a 11 mois
Day10MonthsAgo: Il y a 10 mois
Day9MonthsAgo: Il y a 9 mois
Day8MonthsAgo: Il y a 8 mois
Day7MonthsAgo: Il y a 7 mois
Day6MonthsAgo: Il y a 6 mois
Day5MonthsAgo: Il y a 5 mois
Day4MonthsAgo: Il y a 4 mois
Day3MonthsAgo: Il y a 3 mois
Day2MonthsAgo: Il y a 2 mois
Day1MonthAgo: Il y a un mois
Day4WeeksAgo: Il y a 4 semaines
Day3WeeksAgo: Il y a 3 semaines
Day2WeeksAgo: Il y a 2 semaines
Day1WeekAgo: Il y a une semaine
Day6DaysAgo: Il y a 6 jours
Day5DaysAgo: Il y a 5 jours
Day4DaysAgo: Il y a 4 jours
Day3DaysAgo: Il y a 3 jours
Day2DaysAgo: Il y a 2 jours
DayYesterday: Hier
DayToday: Aujourd’hui
DayTomorrow: Demain
DayIn2Days: Dans 2 jours
DayIn3Days: Dans 3 jours
DayIn4Days: Dans 4 jours
DayIn5Days: Dans 5 jours
DayIn6Days: Dans 6 jours
DayIn1Week: Dans une semaine
DayIn2Week: Dans 2 semaines
DayIn3Week: Dans 3 semaines
DayIn4Week: Dans 4 semaines
DayIn1Month: Dans un mois
DayIn2Months: Dans 2 mois
DayIn3Months: Dans 3 mois
DayIn4Months: Dans 4 mois
DayIn5Months: Dans 5 mois
DayIn6Months: Dans 6 mois
DayIn7Months: Dans 7 mois
DayIn8Months: Dans 8 mois
DayIn9Months: Dans 9 mois
DayIn10Months: Dans 10 mois
DayIn11Months: Dans 11 mois
DayInMoreThanAYear: Plus qu’un an à partir de maintenant

# Errors
NotFound: Page non trouvée
Gone: Page a disparu
