# Translators
# assistant.cssyd@gmail.com

# Logo
Logo title@Text: #{title} Logo

# Home Page
HomeDescription title@Text: #{title}: Waar kan ik gaan dansen? Vind vandaag sociale dans feesten. Ongeacht of u zoekt naar Salsa, Bachata, Kizomba, Mambo, Cha-Cha-Cha, Tango, Zouk, Swing, Lindy Hop, of nog een andere dans, u vindt het hier.
HomeSubtitleQuestion: Waar kan ik gaan dansen?
HomeFormSearch: Zoeken
HomeAdvancedLabel: Geavanceerd

# Advanced search
AdvancedSearchTitle: Geavanceerd zoeken
AdvancedSearchDescription: Vindt exact de feesten die u zoekt.
AdvancedSearchFormLocationLabel: Locatie
AdvancedSearchFormDistanceLabel: Afstand
AdvancedSearchFormBeginLabel: Van
AdvancedSearchFormEndLabel: Tot
AdvancedSearchFormDanceStyleLabel: Dansstijl
AdvancedSearchFormSubmit: Zoeken

# Locate me button
LocateMePlaceholder: Locatie ingeven
LocateMeLocation: Mijn locatie
LocateMeUnable: Localiseren mislukt..
LocateMeInProgress: Localiseren…
LocateMeDone: Gelocaliseerd
LocateMeHelpBefore: Druk op 'Mijn locatie' om uw huidige locatie te gebruiken.
LocateMeHelpAfter: Uw huidige locatie zal worden gebruikt tenzij u een andere locatie ingeeft.

# Explore
ExploreTitle: Ontdek de wereld van de sociale dans!
ExploreDescription: Sociale dans bestaat over de hele wereld, ontdek waar je heen kunt!
ExploreButton: Verken
ExploreUpcomingParties number@String: #{number} komende feesten
ExploreSkylineAlt location@Text: Night-time skyline van #{location}

## Footer
FooterGeocodingAttribution: Geocodering door OpenStreetMaps Nominatim
FooterOpenstreetmapCopyright: © OpenStreetMap medewerkers

# Navbar
NavFind: Vind feesten
NavSubmitParty: Feest toevoegen
NavAccount: Account
NavOrganiser: Organisatorprofiel
NavParties: Mijn feesten
NavLanguage: Taal
NavAdmin: Beheerdersoverzicht
NavSignUp: Registreren
NavLogIn: Aanmelden
NavLogOut: Afmelden

# Form messages
InvalidLatitude lat@String: Ongeldige breedtegraad: #{lat}
InvalidLongitude lon@String: Ongeldige lengtegraad: #{lon}
DistanceTooGreat distance@String: Afstand te groot: #{distance} km
EndBeforeBegin: The einddatum lag vóór de begindatum.
EndTooFarAhead: Het zoekdatumbereik was te groot.
AddressOrCoordinates: Voer ofwel een adres, ofwel coördinaten in.

# Search Results

## Title

### Without dance style
SearchTitleAroundYourLocationToday: Socialedansfeesten vandaag bij jou in de buurt
SearchTitleAroundYourLocationOnDay day@String: Socialedansfeesten op #{day} bij jou in de buurt
SearchTitleAroundYourLocationFromTo begin@String end@String: Socialedansfeesten tussen #{begin} en #{end} bij jou in de buurt
SearchTitleAroundAddressToday address@Text: Socialedansfeesten vandaag in de buurt van #{address}
SearchTitleAroundAddressOnDay address@Text day@String: Socialedansfeesten op #{day} in de buurt van #{address}
SearchTitleAroundAddressFromTo address@Text begin@String end@String: Socialedansfeesten tussen #{begin} en #{end} bij in de buurt van #{address}

### With dance style
SearchTitleDanceStyleAroundYourLocationToday danceStyle@Text: #{danceStyle} feesten vandaag bij jou in de buurt
SearchTitleDanceStyleAroundYourLocationOnDay danceStyle@Text day@String: #{danceStyle} feesten op #{day} bij jou in de buurt
SearchTitleDanceStyleAroundYourLocationFromTo danceStyle@Text begin@String end@String: #{danceStyle} feesten tussen #{begin} en #{end} bij jou in de buurt
SearchTitleDanceStyleAroundAddressToday danceStyle@Text address@Text: #{danceStyle} feesten vandaag in de buurt van #{address}
SearchTitleDanceStyleAroundAddressOnDay danceStyle@Text address@Text day@String: #{danceStyle} feesten op #{day} in de buurt van #{address}
SearchTitleDanceStyleAroundAddressFromTo danceStyle@Text address@Text begin@String end@String: #{danceStyle} feesten tussen #{begin} en #{end} bij in de buurt van #{address}

## Description

### Without dance style
SearchDescriptionAroundYourLocationToday: Een lijst van socialedansfeesten vandaag bij jou in de buurt
SearchDescriptionAroundYourLocationOnDay day@String: Een lijst van socialedansfeesten op #{day} bij jou in de buurt
SearchDescriptionAroundYourLocationFromTo begin@String end@String: Een lijst van socialedansfeesten tussen #{begin} en #{end} bij jou in de buurt
SearchDescriptionAroundAddressToday address@Text: Een lijst van socialedansfeesten vandaag in de buurt van #{address}
SearchDescriptionAroundAddressOnDay address@Text day@String: Een lijst van socialedansfeesten op #{day} in de buurt van #{address}
SearchDescriptionAroundAddressFromTo address@Text begin@String end@String: Een lijst van socialedansfeesten tussen #{begin} en #{end} in de buurt van #{address}

### With dance style
SearchDescriptionDanceStyleAroundYourLocationToday danceStyle@Text: Een lijst van #{danceStyle} feesten vandaag bij jou in de buurt
SearchDescriptionDanceStyleAroundYourLocationOnDay danceStyle@Text day@String: Een lijst van #{danceStyle} feesten op #{day} bij jou in de buurt
SearchDescriptionDanceStyleAroundYourLocationFromTo danceStyle@Text begin@String end@String: Een lijst van #{danceStyle} feesten tussen #{begin} en #{end} bij jou in de buurt
SearchDescriptionDanceStyleAroundAddressToday danceStyle@Text address@Text: Een lijst van #{danceStyle} feesten vandaag in de buurt van #{address}
SearchDescriptionDanceStyleAroundAddressOnDay danceStyle@Text address@Text day@String: Een lijst van #{danceStyle} feesten op #{day} in de buurt van #{address}
SearchDescriptionDanceStyleAroundAddressFromTo danceStyle@Text address@Text begin@String end@String: Een lijst van #{danceStyle} feesten tussen #{begin} en #{end} in de buurt van #{address}

## Search Errors
SearchNoParties: Geen feesten gevonden voor deze dag.
SearchPosterAlt title@Text day@String: Poster voor #{title} op #{day}.
SearchNoResults: We hebben nog geen informatie over deze locatie.
SearchNoResultsHelp: We hebben uw hulp nodig om meer informatie te vergaren over deze locatie. Contacteer alstublieft organisatoren in de buurt en vertel hen over deze pagina. Als u feesten organiseert in deze buurt, meldt u dan aan om uw feesten hier gratis te adverteren.


SearchNavEarlier: Vorige
SearchNavLater: Volgende

# Party Page
PartyTitleScheduled title@Text: #{title}
PartyTitleCancelled title@Text: GEANNULEERD: #{title}
PartyDescription description@Text: #{description}

PartyAddress address@Text: #{address}
PartyOrganiser name@Text: Organisator: #{name}
PartyOrganiserTitle organiserName@Text: Organisatorprofiel van #{organiserName}
PartyPrice price@Text: Prijs: #{price}
PartyHomepage: Website
PartyHomepageTitle partyTitle@Text: Website van #{partyTitle}
PartyDownloadCalendarEvent: Download evenement
PartyDownloadCalendarEventTitle partyTitle@Text: Kalender evenement voor #{partyTitle} downloaden
PartyAddToGoogleCalendar: Toevoegen aan Google Calendar
PartyAddToGoogleCalendarTitle partyTitle@Text: #{partyTitle} aan Google Calendar toevoegen

PartyDescriptionDay day@String: op #{day}
PartyDescriptionDateTime day@String start@String: op #{day} om #{start}
PartyDescriptionOrganiser name@Text: door #{name}
PartyDescriptionAddress address@Text: adres: #{address}

ExternalEventCaution: Evenement gevonden op het web. Gelieve voorzichtig om te gaan met deze informatie.

# Organiser Page
OrganiserTitle name@Text: Organisatorprofiel: #{name}
OrganiserHomepage: Website
OrganiserHomepageTitle name@Text: Website van #{name}
OrganiserDescription name@Text: Het organisatorprofiel van #{name} en een lijst van hun komende socialedansfeesten
OrganiserName name@Text: Organisator: #{name}
OrganiserUpcomingParties: Komende feesten
OrganiserNoUpcomingParties: Geen komende feesten
OrganiserCalendarTitle: Kalender URL
OrganiserCalendarExplanation: Voeg al deze evenementen automatisch toe aan je agenda door je te abonneren via deze link:


# Poster
PosterAltFull title@Text day@String organiser@Text: Poster voor #{title} op #{day} door #{organiser}.
PosterAltTitle title@Text day@String: Poster voor #{title} op #{day}
PosterAltSchedule title@Text recurrenceDescription@Text organiser@Text: Poster voor #{title}, #{recurrenceDescription} door #{organiser}

# Registration
RegistrationTitle: Registreren
RegistrationDescription: Registreer een account
RegistrationEmailAddressLabel: E-mailadres
RegistrationPassphraseLabel: Wachtwoord
RegistrationConfirmPassphraseLabel: Bevestig wachtwoord
RegistrationSignUpButton: Registreer
RegistrationLogInButton: Aanmelden
RegistrationErrorAccountAlreadyExists: Een account met dit e-mailadres is reeds in gebruik.

# Login
LoginTitle: Aanmelden
LoginDescription: Meld u aan
LoginEmailAddressLabel: E-mailadres
LoginPassphraseLabel: Wachtwoord
LoginLogInButton: Aanmelden
LoginSignUpButton: Registreer

# Verification Email
VerificationEmailSubject title@Text: #{title} e-mailverificatie
VerificationEmailTitle title@Text: #{title} registratie
VerificationEmailTextCTA: Om uw e-mailadres te verifiëren gelieve op de volgende link te klikken:
VerificationEmailHtmlCTA: Gelieve uw e-mailadres te verifiëren door op de volgende link te klikken.
VerificationEmailButton: E-mail verifiëren
VerificationEmailInvitation: Hopelijk tot ziens.
VerificationEmailExplanation title@Text: U krijgt deze e-mail omdat u probeerde te registreren bij #{title}

VerificationEmailFailure: Kan verificatie-e-mail niet verzenden.
VerificationErrorAlreadyVerified: Dit account is reeds geverifieerd.

# Account Page
AccountOverviewTitle: Account
AccountEmailAddress emailAddress@Text: E-mailadres: #{emailAddress}
AccountVerificationTitle: Accountverificatie
AccountVerificationWarning: Uw account is nog niet geverifieerd. U kan nog geen feesten indienen.
AccountVerificationCheckEmail: Controleer uw mailbox voor een verificatie-e-mail.
AccountVerificationCheckEmailDisclaimer: Als u de verificatie-e-mail niet ziet, controleer dan ook de spam-map. We doen echter ons best om te voorkomen dat er e-mails in de spam-map belanden. Als u nog steeds geen e-mail vindt, gelieve dan de beheerders te contacteren.
AccountVerificationResendButton: Verificatie-e-mail opnieuw versturen
AccountDangerZoneTitle: Gevarenzone
AccountDeleteButton: Verwijder account
AccountDeleteWarning: Weet u zeker dat u uw account wilt verwijderen? Deze actie kunt u niet ongedaan maken.

# Organiser Profile
OrganiserProfileTitle: Organisatorprofiel
OrganiserDisplayNameLabel: Weergavenaam
OrganiserHomepageLabel: Website
OrganiserConsentReminderLabel: Ik wil eraan herinnerd worden om mijn feesten te adverteren.
OrganiserConsentReminderHelp: We zullen u nooit meer dan één herinnering sturen. U kan dit elk moment stopzetten.
OrganiserSubmitButton: Indienen
OrganiserViewPublicProfileButton: Bekijk openbaar profiel
OrganiserSaveSuccess: Organisatorprofiel opgeslagen

# Submit
SubmitTitle: Voeg uw feest toe
SubmitSingleParty: Enkel feest
SubmitRecurringParty: Herhaaldelijk feest
SubmitSinglePartyExplanation1: Een enkel feest gebeurt maar eenmalig, op een bepaalde dag.
SubmitSinglePartyExplanation2: U kan het later nog steeds aanpassen, annuleren of verwijderen.
SubmitRecurringPartyExplanation1: Een herhaaldelijk feest gebeurt meerdere keren. Bijvoorbeeld elke vrijdag.
SubmitRecurringPartyExplanation2: Wanneer u een herhaaldelijk feest instelt, genereert de site automatisch toekomstige feesten.
SubmitRecurringPartyExplanation3: Als u een herhaaldelijk feest aanpast, worden alle toekomstige versies ervan ook automatisch aangepast.
SubmitRecurringPartyExplanation4: Als u een herhaaldelijk feest verwijdert, worden alle toekomstige versies ervan geannuleerd, en zullen er verder geen gegenereerd worden.

# Your parties
YourPartiesTitle: Uw feesten
YourPartiesPartiesSubtitle: Feesten
YourPartiesSchedulesSubtitle: Herhaaldelijke feesten
YourPartiesSubmitButton: Feest indienen
YourPartiesNoParties: U heeft nog geen feesten indienen.
YourPartiesEditPartyButton: Bewerken
YourPartiesEditScheduleButton: Bewerken
YourPartiesPublicPartyButton: Openbaar profiel
YourPartiesDuplicatePartyButton: Dupliceren
YourPartiesCancelPartyButton: Annuleer
YourPartiesUnCancelPartyButton: Ontannuleren
YourPartiesDeletePartyWarning: Weet u zeker dat u dit feest wilt verwijderen? Deze actie kunt u niet ongedaan maken.
YourPartiesDeletePartyButton: Verwijderen

# Party form
PartyFormTitleLabel: Titel
PartyFormDayLabel: Dag
PartyFormAddressLabel: Adres
PartyFormDescriptionLabel: Beschrijving
PartyFormStartLabel: Start
PartyFormHomepageLabel: Website
PartyFormPriceLabel: Prijs
PartyFormPriceHelp: Schrijf GRATIS als het feest gratis is.
PartyFormPosterLabel: Poster
PartyFormPosterChooseInstruction: Kies een afbeelding
PartyFormPosterNoPoster: Geen poster geselecteerd
PartyFormBackButton: Terug

# Account Party
AccountPartyErrorNotYourParty: Dit is niet uw feest.

# Submit Party
SubmitPartyTitle: Feest indienen
SubmitPartyButton: Indienen
SubmitPartySuccess: Feest succesvol ingediend
SubmitPartyErrorUnverified: Uw account moet geverifieerd worden vooraleer u feesten kan indienen.
SubmitPartyErrorNoOrganiser: U moet eerst een organisatorprofiel aanmaken vooraleer u een feest kan indienen.

# Edit Party
EditPartyTitle: Feest bewerken
EditPartyButton: Opslaan
EditPartySuccess: Feest succesfully bewerkt
EditPartyPublicPartyProfile: Openbaar feestprofiel
EditPartyDayHelp: U kan de dag niet meer bewerken. Als u dat wilt doen, kan u dit feest annuleren en en nieuw feest aanmaken, of dit feest dupliceren en het feest herorganiseren.
EditPartyErrorNotYourParty: Dit is niet uw feest. U kan dit feest niet bewerken.

# Duplicate Party
DuplicatePartyTitle: Feest dupliceren
DuplicatePartyButton: Dupliceren

# Cancel party
CancelPartyErrorNotYourParty: Dit is niet uw feest. U kan dit feest niet annuleren.

# Un-Cancel party
UnCancelPartyErrorNotYourParty: Dit is niet uw feest. U kan dit feest niet ontannuleren.

# Delete party
DeletePartyErrorNotYourParty: Dit is niet uw feest. U kan dit feest niet verwijderen.

# Schedule Form
ScheduleFormTitleLabel: Titel
ScheduleFormRecurrenceLabel: Herhaling
ScheduleFormAddressLabel: Address
ScheduleFormDescriptionLabel: Beschrijving
ScheduleFormStartLabel: Start
ScheduleFormHomepageLabel: Website
ScheduleFormPriceLabel: Prijs
ScheduleFormPriceHelp: Schrijf GRATIS als het feest gratis is.
ScheduleFormPosterLabel: Poster
ScheduleFormPosterChooseInstruction: Kies een afbeelding
ScheduleFormPosterNoPoster: Geen poster geselecteerd
ScheduleFormBackButton: Terug


## Recurrence
RecurrenceWeeklyDescription weekday@String: Elke week op #{weekday}
RecurrenceMonthlyDescriptionEvery: Elke
RecurrenceMonthlyDescriptionEveryFirst: Elke eerste
RecurrenceMonthlyDescriptionEverySecond: Elke tweede
RecurrenceMonthlyDescriptionEveryThird: Elke derde
RecurrenceMonthlyDescriptionEveryFourth: Elke vierde
RecurrenceMonthlyDescriptionEveryLast: Elke laatste
RecurrenceMonthlyDescriptionEverySecondToLast: Elke tweede laatste
RecurrenceMonthlyDescriptionEveryThirdToLast: Elke derde laatste
RecurrenceMonthlyDescriptionEveryFourthToLast: Elke vierde laatste
RecurrenceMonthlyDescriptionDayOfWeekFirst weekday@String: Elke eerste #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekSecond weekday@String: Elke tweede #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekThird weekday@String: Elke derde #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekFourth weekday@String: Elke vierde #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekLast weekday@String: Elke laatste #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekSecondToLast weekday@String: Elke tweede laatste #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekThirdToLast weekday@String: Elke derde laatste #{weekday} van de maand
RecurrenceMonthlyDescriptionDayOfWeekFourthToLast weekday@String: Elke vierde laatste #{weekday} van de maand

# Submit Schedule
SubmitScheduleTitle: Herhaaldelijk feest
SubmitScheduleButton: Indienen
SubmitScheduleSuccess: Herhaaldelijk feest succesvol toegevoegd
SubmitScheduleErrorUnverified: Uw account moet geverifieerd worden vooraleer u herhaaldelijke feesten kan indienen.
SubmitScheduleErrorNoOrganiser: U moet eerst een organisatorprofiel aanmaken vooraleer u een herhaaldelijk feest kan indienen.

# Account Schedule
AccountScheduleParties: Gegenereerde feesten

# Edit Schedule
EditScheduleTitle: Herhaaldelijk feest aanpassen
EditScheduleButton: Opslaan
EditScheduleSuccess: Herhaaldelijk feest succesvol opgeslagen
EditScheduleErrorNotYourSchedule: Dit is niet uw herhaaldelijk feest. U kan dit herhaaldelijk feest niet bewerken.

# Your schedules
YourSchedulesTitle: Uw herhaaldelijke feesten
YourSchedulesSubmitButton: herhaaldelijk feest indienen
YourSchedulesNoSchedules: U heeft nog geen herhaaldelijke feesten ingediend.
YourSchedulesEditScheduleButton: Aanpassen
YourSchedulesDeleteScheduleWarning: Weet u zeker dat u dit feest wilt verwijderen? Deze actie kunt u niet ongedaan maken. Feesten die door dit herhalingsschema zijn aangemaakt zullen niet verwijderd worden.
YourSchedulesDeleteScheduleButton: Verwijderen
ScheduleTitle title@Text: #{title}

# Delete schedule
DeleteScheduleErrorNotYourSchedule: Dit is niet uw herhaaldelijk feest. U kan dit herhaaldelijk feest niet verwijderen.


# Unsubscribe Reminder 
UnsubReminderTitle: Uitgeschreven
UnsubReminderDescription: U krijgt voortaan geen herinneringsemails meer.

# Google Maps
GoogleMapAlt location@Text: Kaart van de omgeving van #{location}

# Pagination
PaginationPrevious: Vorige
PaginationNext: Volgende

# All Dance Styles
DanceStyleFilter: Filter
AllDanceStyles: Alle dansstijlen
Salsa: Salsa
Bachata: Bachata
ChaChaCha: Cha-Cha-Cha
Kizomba: Kizomba
Zouk: Zouk
LindyHop: Lindy Hop
Tango: Tango
WestCoastSwing: West Coast Swing

# Auto day
DayMoreThanAYearAgo: meer dan een jaar geleden
Day11MonthsAgo: 11 maanden geleden
Day10MonthsAgo: 10 maanden geleden
Day9MonthsAgo: 9 maanden geleden
Day8MonthsAgo: 8 maanden geleden 
Day7MonthsAgo: 7 maanden geleden
Day6MonthsAgo: 6 maanden geleden
Day5MonthsAgo: 5 maanden geleden
Day4MonthsAgo: 4 maanden geleden
Day3MonthsAgo: 3 maanden geleden    
Day2MonthsAgo: 2 maanden geleden
Day1MonthAgo: een maand geleden
Day4WeeksAgo: 4 weken geleden
Day3WeeksAgo: 3 weken geleden
Day2WeeksAgo: 2 weken geleden
Day1WeekAgo: een week geleden
Day6DaysAgo: 6 dagen geleden
Day5DaysAgo: 5 dagen geleden
Day4DaysAgo: 4 dagen geleden
Day3DaysAgo: 3 dagen geleden
Day2DaysAgo: eergisteren
DayYesterday: gisteren
DayToday: vandaag
DayTomorrow: morgen
DayIn2Days: overmorgen
DayIn3Days: over 3 dagen
DayIn4Days: over 4 dagen
DayIn5Days: over 5 dagen
DayIn6Days: over 6 dagen
DayIn1Week: over een week
DayIn2Week: over 2 weken
DayIn3Week: over 3 weken
DayIn4Week: over 4 weken
DayIn1Month: over een maand
DayIn2Months: over 2 maanden
DayIn3Months: over 3 maanden
DayIn4Months: over 4 maanden
DayIn5Months: over 5 maanden
DayIn6Months: over 6 maanden
DayIn7Months: over 7 maanden
DayIn8Months: over 8 maanden
DayIn9Months: over 9 maanden
DayIn10Months: over 10 maanden
DayIn11Months: over 11 maanden
DayInMoreThanAYear: over meer dan een jaar

# Errors
NotFound: Pagina niet gevonden
Gone: Pagina is verdwenen
