name:                salsa-party-web-server-gen
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - aeson
  - aeson-pretty
  - bytestring
  - cache
  - containers
  - data-default
  - deepseq
  - filepath
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-persistent
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - http-client
  - microlens
  - monad-logger
  - mtl
  - password
  - path-io
  - path-pieces
  - persistent
  - persistent-sqlite
  - pretty-show
  - salsa-party-web-server
  - shakespeare
  - sydtest
  - sydtest-aeson
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-wai
  - sydtest-yesod
  - text
  - time
  - typed-uuid
  - unliftio
  - uuid
  - yesod
  - yesod-auth
  - yesod-core


benchmarks:
  smos-api-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - cache
    - criterion
    - genvalidity
    - genvalidity-criterion
    - monad-logger
    - persistent
    - salsa-party-web-server
    - salsa-party-web-server-gen
    - sydtest
    - time

tests:
  salsa-party-web-server-gen-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - aeson-pretty
    - bytestring
    - cache
    - containers
    - data-default
    - esqueleto
    - filepath
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-persistent
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-typed-uuid
    - http-client
    - ical
    - microlens
    - monad-logger
    - mtl
    - password
    - path
    - path-io
    - path-io
    - path-pieces
    - persistent
    - persistent-sqlite
    - pretty-show
    - salsa-party-web-server
    - salsa-party-web-server-gen
    - shakespeare
    - sydtest
    - sydtest-aeson
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod
    - text
    - time
    - typed-uuid
    - unliftio
    - uuid
    - yesod
    - yesod-auth
    - yesod-core
