name:                salsa-party-web-server-gen
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - bytestring
  - cache
  - filepath
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-persistent
  - genvalidity-sydtest
  - genvalidity-time
  - genvalidity-typed-uuid
  - http-client
  - microlens
  - monad-logger
  - mtl
  - password
  - path-io
  - persistent
  - persistent-sqlite
  - pretty-show
  - salsa-party-data
  - salsa-party-data-gen
  - salsa-party-web-server
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-wai
  - sydtest-yesod
  - text
  - time
  - yesod
  - yesod-auth


benchmarks:
  salsa-party-web-server-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - QuickCheck
    - cache
    - criterion
    - genvalidity
    - monad-logger
    - persistent
    - salsa-party-data
    - salsa-party-data-gen
    - salsa-party-web-server
    - salsa-party-web-server-gen
    - sydtest
    - time

tests:
  salsa-party-web-server-gen-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - aeson-pretty
    - bytestring
    - cache
    - containers
    - esqueleto
    - genvalidity
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - http-client
    - ical
    - monad-logger
    - mtl
    - password
    - path
    - path-io
    - path-io
    - path-pieces
    - persistent
    - pretty-show
    - salsa-party-data
    - salsa-party-data-gen
    - salsa-party-web-server
    - salsa-party-web-server-gen
    - shakespeare
    - sydtest
    - sydtest-aeson
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-yesod
    - text
    - time
    - typed-uuid
    - unliftio
    - uuid
    - yesod
    - yesod-auth
    - yesod-core
