name:                salsa-party-web-server-webdriver
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - mtl
  - persistent
  - salsa-party-web-server
  - salsa-party-web-server-gen
  - sydtest
  - sydtest-webdriver
  - sydtest-webdriver-yesod
  - text
  - time
  - webdriver
  - yesod

tests:
  salsa-party-web-server-webdriver-test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-sydtest
    - mtl
    - password
    - persistent
    - pretty-show
    - salsa-party-web-server
    - salsa-party-web-server-gen
    - salsa-party-web-server-webdriver
    - sydtest
    - sydtest-webdriver
    - sydtest-webdriver-screenshot
    - sydtest-webdriver-yesod
    - time
    - typed-uuid
    - uuid
    - webdriver
    - yesod
