name:                salsa-party-data-gen
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - microlens
  - monad-logger
  - password
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - salsa-party-data
  - sydtest
  - text
  - yesod-form

benchmarks:
  salsa-party-data-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - criterion
    - genvalidity-criterion
    - salsa-party-data
    - salsa-party-data-gen


tests:
  salsa-party-data-gen-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-persistent
    - path-pieces
    - persistent
    - salsa-party-data
    - salsa-party-data-gen
    - sydtest
    - sydtest-aeson
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - time
    - unliftio
