name:                salsa-party-web-server
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - JuicyPixels
  - JuicyPixels-extra
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-ses
  - autodocodec
  - autodocodec-yaml
  - base64-bytestring
  - blaze-html
  - bytestring
  - cache
  - case-insensitive
  - clock
  - conduit
  - containers
  - cryptohash-sha256
  - data-default
  - deepseq
  - edit-distance
  - envparse
  - esqueleto
  - fast-logger
  - file-embed
  - hashable
  - http-api-data
  - http-client
  - http-client-tls
  - http-date
  - http-types
  - ical
  - looper
  - microlens
  - monad-logger
  - mtl
  - network-uri
  - optparse-applicative
  - password
  - path
  - path-io
  - path-pieces
  - persistent
  - persistent-sqlite
  - pretty-relative-time
  - pretty-show
  - random
  - random-shuffle
  - resourcet
  - retry
  - safe
  - safe-coloured-text
  - scalpel
  - scientific
  - shakespeare
  - tagsoup
  - template-haskell
  - text
  - text-icu
  - time
  - token-limiter-concurrent
  - typed-process
  - typed-uuid
  - unliftio
  - uuid
  - validity
  - validity-bytestring
  - validity-persistent
  - validity-text
  - validity-time
  - wai
  - wai-extra
  - warp
  - webdriver
  - xml-conduit
  - yaml
  - yesod
  - yesod-auth
  - yesod-autoreload
  - yesod-core
  - yesod-form
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote
  - zip-archive

executables:
  salsa-party-web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server

tests:
  salsa-party-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - path
    - path-io
    - sydtest
    - text
