name:                salsa-party-web-server
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - data-default
  - envparse
  - esqueleto
  - http-client
  - http-client-tls
  - monad-logger
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - shakespeare
  - template-haskell
  - text
  - time
  - token-limiter
  - validity
  - validity-text
  - validity-time
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-autoreload
  - yesod-static
  - yesod-static
  - yesod-static-remote

executables:
  salsa-party-web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server

tests:
  salsa-party-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - http-client
    - http-types
    - monad-logger
    - mtl
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - salsa-party-web-server
    - sydtest
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod
    - text
    - time
    - yesod
