name:                salsa-party-web-server
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - data-default
  - envparse
  - monad-logger
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - shakespeare
  - template-haskell
  - text
  - time
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-static

executables:
  salsa-party-web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server

tests:
  salsa-party-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: hspec-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - hspec
    - monad-logger
    - persistent
    - persistent-sqlite
    - salsa-party-web-server
    - text
    - yesod
    - yesod-test
