name:                salsa-party-web-server
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - JuicyPixels
  - JuicyPixels-extra
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-ses
  - base64-bytestring
  - blaze-html
  - bytestring
  - conduit
  - cryptohash-sha256
  - data-default
  - directory
  - envparse
  - esqueleto
  - exceptions
  - file-embed
  - filepath
  - http-client
  - http-client-tls
  - http-date
  - http-types
  - looper
  - microlens
  - monad-logger
  - mtl
  - network-uri
  - optparse-applicative
  - password
  - path
  - path-io
  - path-pieces
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-relative-time
  - pretty-show
  - random
  - resourcet
  - shakespeare
  - template-haskell
  - text
  - time
  - token-limiter
  - unliftio
  - uuid
  - typed-uuid
  - validity
  - validity-persistent
  - validity-text
  - validity-time
  - wai
  - wai-extra
  - warp
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-auth
  - yesod-autoreload
  - yesod-core
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  salsa-party-web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server

  salsa-party-web-server-e2e:
    main:                Main.hs
    source-dirs:         e2e
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linkcheck
    - monad-logger
    - network-uri
    - salsa-party-web-server
    - seocheck
    - sydtest

tests:
  salsa-party-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - conduit
    - esqueleto
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-persistent
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - genvalidity-typed-uuid
    - http-client
    - http-types
    - microlens
    - monad-logger
    - mtl
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - salsa-party-web-server
    - sydtest
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod
    - text
    - time
    - yesod
    - yesod-auth
    - yesod-core
