name:                salsa-party-web-server-e2e
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - monad-logger
  - network-uri
  - salsa-party-web-server
  - sydtest
  - sydtest-yesod
  - text
  - yesod-auth
  - linkcheck
  - monad-logger
  - network-uri
  - salsa-party-web-server
  - seocheck
  - sydtest
  - sydtest-yesod
  - text
  - yesod-auth

executables:
  salsa-party-web-server-e2e:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server
    - salsa-party-web-server-e2e
