name:                salsa-party-web-server-e2e
version:             0.0.0.0
license:             AllRightsReserved

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - genvalidity-sydtest
  - ical
  - linkcheck
  - monad-logger
  - network-uri
  - salsa-party-data
  - salsa-party-data-gen
  - salsa-party-web-server
  - salsa-party-web-server-gen
  - scalpel
  - seocheck
  - sydtest
  - sydtest-yesod
  - text
  - time
  - yesod-auth

executables:
  salsa-party-web-server-e2e:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa-party-web-server-e2e

tests:
  salsa-party-web-server-e2e-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-client
    - salsa-party-web-server-e2e
    - salsa-party-web-server-gen
    - sydtest
    - sydtest-yesod
