CREATE TABLE "user"("id" INTEGER PRIMARY KEY,"email_address" VARCHAR NOT NULL,"passphrase_hash" VARCHAR NOT NULL,"verification_key" VARCHAR NULL,"created" TIMESTAMP NOT NULL,CONSTRAINT "unique_user_email_address" UNIQUE ("email_address"));
CREATE TABLE "organiser"("id" INTEGER PRIMARY KEY,"uuid" BLOB NOT NULL,"slug" VARCHAR NULL DEFAULT null,"user" INTEGER NOT NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT,"name" VARCHAR NOT NULL,"homepage" VARCHAR NULL DEFAULT NULL,"created" TIMESTAMP NOT NULL,"modified" TIMESTAMP NULL DEFAULT NULL,CONSTRAINT "unique_organiser_u_u_i_d" UNIQUE ("uuid"),CONSTRAINT "unique_organiser_slug" UNIQUE ("slug"),CONSTRAINT "unique_organiser_user" UNIQUE ("user"));
CREATE TABLE "organiser_reminder"("id" INTEGER PRIMARY KEY,"organiser" INTEGER NOT NULL REFERENCES "organiser" ON DELETE RESTRICT ON UPDATE RESTRICT,"consent" BOOLEAN NOT NULL DEFAULT false,"secret" BLOB NOT NULL DEFAULT NULL,"last" TIMESTAMP NULL,CONSTRAINT "unique_organiser_reminder_organiser" UNIQUE ("organiser"),CONSTRAINT "unique_organiser_reminder_secret" UNIQUE ("secret"));
CREATE TABLE "place"("id" INTEGER PRIMARY KEY,"query" VARCHAR NOT NULL,"lat" INTEGER NOT NULL,"lon" INTEGER NOT NULL,CONSTRAINT "unique_place_query" UNIQUE ("query"));
CREATE TABLE "party"("id" INTEGER PRIMARY KEY,"uuid" BLOB NOT NULL,"slug" VARCHAR NULL DEFAULT null,"organiser" INTEGER NOT NULL REFERENCES "organiser" ON DELETE RESTRICT ON UPDATE RESTRICT,"title" VARCHAR NOT NULL,"description" VARCHAR NULL,"day" DATE NOT NULL,"start" TIME NULL,"homepage" VARCHAR NULL,"price" VARCHAR NULL DEFAULT NULL,"cancelled" BOOLEAN NOT NULL DEFAULT 0,"created" TIMESTAMP NOT NULL,"modified" TIMESTAMP NULL DEFAULT NULL,"place" INTEGER NOT NULL REFERENCES "place" ON DELETE RESTRICT ON UPDATE RESTRICT,"poster" INTEGER NULL DEFAULT NULL,CONSTRAINT "unique_party_u_u_i_d" UNIQUE ("uuid"));
CREATE TABLE "image"("id" INTEGER PRIMARY KEY,"key" INTEGER NOT NULL,"type" VARCHAR NOT NULL,"blob" BLOB NOT NULL,"created" TIMESTAMP NOT NULL,CONSTRAINT "unique_image_key" UNIQUE ("key"));
CREATE TABLE "schedule"("id" INTEGER PRIMARY KEY,"uuid" BLOB NOT NULL,"organiser" INTEGER NOT NULL REFERENCES "organiser" ON DELETE RESTRICT ON UPDATE RESTRICT,"recurrence" BLOB NOT NULL,"title" VARCHAR NOT NULL,"description" VARCHAR NULL,"start" TIME NULL,"homepage" VARCHAR NULL,"price" VARCHAR NULL DEFAULT NULL,"created" TIMESTAMP NOT NULL,"modified" TIMESTAMP NULL DEFAULT NULL,"place" INTEGER NOT NULL REFERENCES "place" ON DELETE RESTRICT ON UPDATE RESTRICT,"poster" INTEGER NULL DEFAULT NULL,CONSTRAINT "unique_schedule_u_u_i_d" UNIQUE ("uuid"));
CREATE TABLE "schedule_party"("id" INTEGER PRIMARY KEY,"schedule" INTEGER NOT NULL REFERENCES "schedule" ON DELETE RESTRICT ON UPDATE RESTRICT,"party" INTEGER NOT NULL REFERENCES "party" ON DELETE RESTRICT ON UPDATE RESTRICT,"scheduled" TIMESTAMP NOT NULL,CONSTRAINT "unique_schedule_party" UNIQUE ("schedule","party"));
CREATE TABLE "importer_metadata"("id" INTEGER PRIMARY KEY,"name" VARCHAR NOT NULL,"last_run" TIMESTAMP NULL,"last_run_end" TIMESTAMP NULL,"last_run_imported" INTEGER NULL,CONSTRAINT "unique_importer_metadata_name" UNIQUE ("name"));
CREATE TABLE "external_event"("id" INTEGER PRIMARY KEY,"uuid" BLOB NOT NULL,"slug" VARCHAR NULL DEFAULT null,"key" VARCHAR NOT NULL,"title" VARCHAR NOT NULL,"description" VARCHAR NULL,"organiser" VARCHAR NULL,"day" DATE NOT NULL,"start" TIME NULL,"homepage" VARCHAR NULL,"price" VARCHAR NULL DEFAULT NULL,"cancelled" BOOLEAN NULL DEFAULT NULL,"created" TIMESTAMP NOT NULL,"modified" TIMESTAMP NULL DEFAULT NULL,"place" INTEGER NOT NULL REFERENCES "place" ON DELETE RESTRICT ON UPDATE RESTRICT,"poster" INTEGER NULL DEFAULT NULL,"importer" INTEGER NOT NULL REFERENCES "importer_metadata" ON DELETE RESTRICT ON UPDATE RESTRICT,"origin" VARCHAR NOT NULL,CONSTRAINT "unique_external_event_u_u_i_d" UNIQUE ("uuid"),CONSTRAINT "unique_external_event_key" UNIQUE ("importer","key"));
CREATE TABLE "static_map"("id" INTEGER PRIMARY KEY,"place" INTEGER NOT NULL REFERENCES "place" ON DELETE RESTRICT ON UPDATE RESTRICT,"key" INTEGER NOT NULL,CONSTRAINT "unique_static_map_place" UNIQUE ("place"));
CREATE TABLE "prospect"("id" INTEGER PRIMARY KEY,"name" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"place" INTEGER NULL DEFAULT NULL REFERENCES "place" ON DELETE RESTRICT ON UPDATE RESTRICT,"external_event" INTEGER NULL DEFAULT null REFERENCES "external_event" ON DELETE RESTRICT ON UPDATE RESTRICT,"created" TIMESTAMP NOT NULL,"modified" TIMESTAMP NULL DEFAULT NULL,CONSTRAINT "unique_prospect_email" UNIQUE ("email"));

-- ATTENTION CODE REVIEWER
-- If this file has been updated, please make sure to check
-- whether this test failed before that happened:
-- "Salsa.Party.DBSpec.Can automatically migrate from the previous database schema"
-- If this test failed beforehand, but this golden test has
-- been updated anyway, that means the current migration is
-- dangerous with respect to the current database.
